<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-26">

<title>Personas Desaparecidas en México</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="tarea02_files/libs/clipboard/clipboard.min.js"></script>
<script src="tarea02_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="tarea02_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="tarea02_files/libs/quarto-html/popper.min.js"></script>
<script src="tarea02_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tarea02_files/libs/quarto-html/anchor.min.js"></script>
<link href="tarea02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tarea02_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="tarea02_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tarea02_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tarea02_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Personas Desaparecidas en México</h1>
<p class="subtitle lead">Tarea 02 — Almacenes y Minería de Datos</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="inicio" class="level1">
<h1>Inicio</h1>
<p>Los derechos humanos buscan asegurar la dignidad de las personas, su propósito radica en salvaguardar y garantizar el bien común sin discriminar por raza, sexo, religión, edad, ideologías, entre otros aspectos. Asimismo, el reconocimiento de los derechos humanos a partir de 1948 (proclamados en la Declaración Universal de los Derechos Humanos por la ONU) señala derechos inherentes a los individuos por el hecho de ser humanos, proporcionando una protección a no sufrir tratos crueles, inhumanos o degradantes.</p>
<p>La desaparición de personas es un problema de seguridad y justicia, es un fenómeno que viola la dignidad del ser humano, la cual se basa en el reconocimiento de la libertad e igualdad en sus derechos. Esta privación de libertad atenta contra los derechos humanos de las personas, afecta a las víctimas y a sus familias, sembrando miedo e incertidumbre en la sociedad.</p>
<p>México es un país que alberga tradiciones y costumbres inigualables, sin embargo, no está exento de ser afectado por la violencia. Los índices de violencia han incrementado con el tiempo y se ha normalizado este fenómeno provocando falta de empatía y solidaridad en la sociedad, evidenciando la desigualdad. Con esto, la desaparición de personas en México ha experimentado un aumento constante y alarmante, generando una profunda crisis de derechos humanos.</p>
<p>El objetivo del presente trabajo es analizar un conjunto de datos con información correspondiente a este fenómeno para identificar discrepancias históricas y aportar una perspectiva fundamentada en datos empíricos que contribuya a dimensionar esta crisis con mayor claridad. Para ello, contamos con un data set con información sobre los registros de las desapariciones de personas en México en formato csv.</p>
<p>Además, en el desarrollo de este trabajo reconocemos la importancia de este tema que nos incumbe a todos como humanidad, es un tema que ha sembrado desesperanza no sólo en México, sino en varias partes del mundo, es por ello que lo debemos tratar con la delicadeza y detalle que merece.</p>
</section>
<section id="crisp-dm" class="level1">
<h1>CRISP-DM</h1>
<section id="etapas" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="etapas">Etapas</h2>
<section id="comprensión-del-negocio" class="level3">
<h3 class="anchored" data-anchor-id="comprensión-del-negocio">Comprensión del Negocio</h3>
<p>La desaparición es una violación a los derechos humanos que representa un desafío para la justicia y la dignidad de las personas. Esta práctica implica la privación de libertad seguida de la negación o el ocultamiento del paradero de la persona, lo que sume a las familias afectadas resulta en un ciclo de angustia y desesperación. Este fenómeno, que ha ido en aumento en México a lo largo de los años, genera un clima de terror e impunidad, consolidándose en una herramienta de represión y control.</p>
<p>Históricamente, el Registro Nacional de Personas Extraviadas o Desaparecidas (RNPED) fungió como la base de datos que integraba la información de personas no localizadas a partir de denuncias ministeriales. Sin embargo, este registro incluía únicamente los casos activos a su fecha de corte, excluyendo información histórica y sin ofrecer un panorama completo del fenómeno.</p>
<p>Con el tiempo, el RNPED evidenció problemas estructurales que limitaron su utilidad, volviéndose una herramienta desactualizada e ineficaz para la búsqueda efectiva de personas. En respuesta a esta deficiencia, y gracias a la presión social ejercida por el movimiento organizado de familias, en noviembre de 2017 se aprobó la Ley General en Materia de Desaparición Forzada de Personas, Desaparición Cometida por Particulares y del Sistema Nacional de Búsqueda de Personas. Esta legislación dio paso a la creación del actual Registro Nacional de Personas Desaparecidas y No Localizadas (RNPDNO).</p>
<p>Este nuevo registro, administrado y coordinado por la Comisión Nacional de Búsqueda de Personas (CNBP), representó una oportunidad para visibilizar la magnitud de las desapariciones y consolidar una herramienta de búsqueda más robusta. No obstante, es crucial subrayar que el RNPDNO refleja únicamente los casos formalmente denunciados ante las autoridades, lo que implica la existencia de una “cifra negra” que no representa la totalidad de las desapariciones en el país.</p>
<p>Por su parte, la Búsqueda Generalizada, una de las diversas estrategias implementadas por la CNBP, es un proceso diseñado para revisar de manera exhaustiva los registros e indicios que permitan localizar a una persona o dar con su paradero. Este proceso se divide en tres etapas fundamentales: la identificación de escenarios de búsqueda, la recopilación y generación de información, y la verificación de los datos.</p>
<p>La información utilizada para el análisis de este trabajo cuenta con información histórica de personas desaparecidas en México, indicando la presencia del registro en RNPED o en RNPDNO, además de información sobre los resultados de la búsqueda generalizada implementada por la CNBP.</p>
<p>En este contexto, el objetivo de aplicar técnicas de Minería de Datos a estos conjuntos de información es descubrir patrones geográficos y temporales sobre las desapariciones en México. Asimismo, al analizar la transición de los datos del RNPED al RNPDNO, la investigación busca identificar cómo este cambio metodológico e institucional afectó la continuidad de los registros, revelando posibles sesgos, omisiones o reclasificaciones en la información oficial.</p>
<h3 class="anchored">
Preguntas de análisis
</h3>
<p>Para establecer el enfoque del análisis sobre los datos se plantean las siguientes preguntas para poder indagar en los patrones que nos muestra la información.</p>
<ul>
<li><p>¿Cuáles son las entidades federativas con mayor índice de desaparecidos en México en los últimos años?</p></li>
<li><p>¿Cómo ha crecido el número de desapariciones en México?</p></li>
<li><p>¿Cuál es la tendencia histórica anual del volumen de desapariciones registradas? ¿Qué entidades federativas concentran la mayor cantidad de casos?</p></li>
<li><p>¿Qué porcentaje y volumen total de registros históricos presentes en el RNPED ya no figuran en la versión pública actual del registro oficial (RNPDNO)?</p></li>
<li><p>¿Existen patrones temporales o geográficos específicos en los registros que fueron presuntamente omitidos durante la transición entre las bases de datos oficiales?</p></li>
<li><p>¿Cómo ha impactado la implementación de la estrategia gubernamental de “Búsqueda Generalizada” en la reclasificación del estatus de búsqueda de las personas registradas?</p></li>
</ul>
<h3 class="anchored">
Criterio de Éxito
</h3>
<p>Con el presente trabajo se busca lograr un análisis exploratorio que derive en hallazgos sobre el conjunto de datos sustentados con evidencia gráfica, cuantificando objetivamente las inconsistencias, omisiones o reclasificaciones entre los registros gubernamentales históricos y actuales. Técnicamente, el éxito se medirá por la capacidad de procesar los datos anidados y generar un archivo completamente limpio y estandarizado que permita una toma de decisiones informada.</p>
</section>
<section id="comprensión-de-los-datos" class="level3">
<h3 class="anchored">Comprensión de los Datos</h3>
<div data-layout-nrow="6">
<div class="card">
<p>Para proceder con el análisis de los datos se cuenta con un dataset con formato CSV que contiene información de los registros de personas desaparecidas en México. A continuación se presenta una descripción de las columnas que contiene el dataset junto con su descripción, tipo de dato y tipo estadístico.</p>
</div>
<div id="1da84e08" class="cell" title="Diccionario de datos" data-execution_count="2">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_778ab th {
  background-color: #60246c;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_778ab td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_778ab tr:hover td {
  background-color: rgb(213, 115, 226);
  color: #000000;
}
#T_778ab_row0_col0, #T_778ab_row0_col1, #T_778ab_row0_col2, #T_778ab_row0_col3, #T_778ab_row1_col0, #T_778ab_row1_col1, #T_778ab_row1_col2, #T_778ab_row1_col3, #T_778ab_row2_col0, #T_778ab_row2_col1, #T_778ab_row2_col2, #T_778ab_row2_col3, #T_778ab_row3_col0, #T_778ab_row3_col1, #T_778ab_row3_col2, #T_778ab_row3_col3, #T_778ab_row4_col0, #T_778ab_row4_col1, #T_778ab_row4_col2, #T_778ab_row4_col3, #T_778ab_row5_col0, #T_778ab_row5_col1, #T_778ab_row5_col2, #T_778ab_row5_col3, #T_778ab_row6_col0, #T_778ab_row6_col1, #T_778ab_row6_col2, #T_778ab_row6_col3, #T_778ab_row7_col0, #T_778ab_row7_col1, #T_778ab_row7_col2, #T_778ab_row7_col3, #T_778ab_row8_col0, #T_778ab_row8_col1, #T_778ab_row8_col2, #T_778ab_row8_col3, #T_778ab_row9_col0, #T_778ab_row9_col1, #T_778ab_row9_col2, #T_778ab_row9_col3, #T_778ab_row10_col0, #T_778ab_row10_col1, #T_778ab_row10_col2, #T_778ab_row10_col3, #T_778ab_row11_col0, #T_778ab_row11_col1, #T_778ab_row11_col2, #T_778ab_row11_col3 {
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_778ab" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_778ab_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Columna</th>
<th id="T_778ab_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Descripción</th>
<th id="T_778ab_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Tipo de dato</th>
<th id="T_778ab_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Tipo estadístico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_778ab_row0_col0" class="data row0 col0">nombrecompleto</td>
<td id="T_778ab_row0_col1" class="data row0 col1">Nombre completo de la persona desaparecida o no localizada según el registro oficial.</td>
<td id="T_778ab_row0_col2" class="data row0 col2">String</td>
<td id="T_778ab_row0_col3" class="data row0 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row1_col0" class="data row1 col0">rnpdno_json</td>
<td id="T_778ab_row1_col1" class="data row1 col1">Booleano que indica si el registro aparece en la extracción de datos vía JSON del portal oficial.</td>
<td id="T_778ab_row1_col2" class="data row1 col2">Booleano (0/1)</td>
<td id="T_778ab_row1_col3" class="data row1 col3">Categórica nominal</td>
</tr>
<tr class="odd">
<td id="T_778ab_row2_col0" class="data row2 col0">entidad_desap</td>
<td id="T_778ab_row2_col1" class="data row2 col1">Estado o entidad federativa donde se reportó el evento de desaparición o se tuvo el último contacto.</td>
<td id="T_778ab_row2_col2" class="data row2 col2">String</td>
<td id="T_778ab_row2_col3" class="data row2 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row3_col0" class="data row3 col0">pre_rnped</td>
<td id="T_778ab_row3_col1" class="data row3 col1">Indica si la fila aparece en el Registro de Personas Desaparecidas en versiones previas a 2018 (RNPED histórico).</td>
<td id="T_778ab_row3_col2" class="data row3 col2">Booleano (0/1)</td>
<td id="T_778ab_row3_col3" class="data row3 col3">Categórica nominal</td>
</tr>
<tr class="odd">
<td id="T_778ab_row4_col0" class="data row4 col0">rnped</td>
<td id="T_778ab_row4_col1" class="data row4 col1">Indica si la fila aparece en el RNPDO, versión original anterior al registro actual.</td>
<td id="T_778ab_row4_col2" class="data row4 col2">Booleano (0/1)</td>
<td id="T_778ab_row4_col3" class="data row4 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row5_col0" class="data row5 col0">rnpdno_csv</td>
<td id="T_778ab_row5_col1" class="data row5 col1">Booleano que indica si el registro está presente en la base de datos del RNPD (registro actual en CSV).</td>
<td id="T_778ab_row5_col2" class="data row5 col2">Booleano (0/1)</td>
<td id="T_778ab_row5_col3" class="data row5 col3">Categórica nominal</td>
</tr>
<tr class="odd">
<td id="T_778ab_row6_col0" class="data row6 col0">bg_1</td>
<td id="T_778ab_row6_col1" class="data row6 col1">Estatus Búsqueda Generalizada 1: clasificación del registro en la primera publicación del 14 de diciembre de 2023.</td>
<td id="T_778ab_row6_col2" class="data row6 col2">Booleano (0/1)</td>
<td id="T_778ab_row6_col3" class="data row6 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row7_col0" class="data row7 col0">estatus_busqueda</td>
<td id="T_778ab_row7_col1" class="data row7 col1">Resultado de la Estrategia Nacional de Búsqueda Generalizada (Censo). Clasifica el caso en categorías: Con indicios/Ubicada, Se busca reportante, Denuncia confirmada, Se requieren datos de identidad, entre otras.</td>
<td id="T_778ab_row7_col2" class="data row7 col2">String</td>
<td id="T_778ab_row7_col3" class="data row7 col3">Categórica nominal</td>
</tr>
<tr class="odd">
<td id="T_778ab_row8_col0" class="data row8 col0">bg_2</td>
<td id="T_778ab_row8_col1" class="data row8 col1">Estatus Búsqueda Generalizada 2: actualización del estatus a partir de la segunda publicación del 27 de diciembre de 2023.</td>
<td id="T_778ab_row8_col2" class="data row8 col2">Booleano (0/1)</td>
<td id="T_778ab_row8_col3" class="data row8 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row9_col0" class="data row9 col0">fub</td>
<td id="T_778ab_row9_col1" class="data row9 col1">Folio Único de Búsqueda: identificador alfanumérico universal (UUID). Llave primaria para rastrear a la persona en todas las versiones del registro.</td>
<td id="T_778ab_row9_col2" class="data row9 col2">String (UUID)</td>
<td id="T_778ab_row9_col3" class="data row9 col3">Categórica nominal</td>
</tr>
<tr class="odd">
<td id="T_778ab_row10_col0" class="data row10 col0">DC_id</td>
<td id="T_778ab_row10_col1" class="data row10 col1">Data Correlation ID: identificador técnico relativo al archivo de origen (JSON o CSV). No es un ID único global, sino de posición en el dataset.</td>
<td id="T_778ab_row10_col2" class="data row10 col2">String</td>
<td id="T_778ab_row10_col3" class="data row10 col3">Categórica nominal</td>
</tr>
<tr class="even">
<td id="T_778ab_row11_col0" class="data row11 col0">fecha_desap</td>
<td id="T_778ab_row11_col1" class="data row11 col1">Fecha registrada de la desaparición o no localización de la persona.</td>
<td id="T_778ab_row11_col2" class="data row11 col2">Fecha (dd/mm/yyyy)</td>
<td id="T_778ab_row11_col3" class="data row11 col3">Numérica discreta (temporal)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como unidad de análisis en este dataset se tiene que cada registro (cada fila) hace referencia a una persona desaparecida y sus variables que giran entorno a ello: nombre completo, lugar de desaparición, el estatus de la búsqueda y la fecha de desaparición. Además, contiene información para estos registros sobre la Búsqueda Generalizada, su presencia en RNPED y/o RNPDNO.</p>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="card quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p>El conjunto de datos contiene <strong>89720</strong> registros de personas desaparecidas en México</p>
</div>
<div class="card quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p>Para cada registro se tienen hasta <strong>13</strong> variables que describen dicho registro</p>
</div>
<div class="card quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p>El periodo que abarca el conjunto de datos va desde <strong>15/03/1964</strong> hasta <strong>04/08/2023</strong></p>
</div>
</div>
</div>
<div class="card">
<h2 class="anchored" data-anchor-id="comprensión-de-los-datos">
Exploración Inicial
</h2>
<p>A partir de la inspección de los registros, se determinó que la unidad de análisis corresponde a un caso individual de una persona desaparecida o nolocalizada. Después del análisis de las columnas encontramos que tenemos tres tipos de información:</p>
<ul>
<li><strong>Identificación del caso:</strong> Tales como el nombre de la persona, el Folio Único de Búsqueda o DC_id (identificador compuesto entre JSON y CSV)</li>
<li><strong>Contexto espacio-tiempo:</strong> Como el estado de la república de la desaparición, la fecha del suceso y el estatus de la búsqueda.</li>
<li><strong>Trazabilidad Institucional:</strong> Aquellas variables que indican la presencia del registro en distintas bases de datos gubernamentales a lo largo del tiempo como RNPED, RNPDNO o BG (Búsqueda Generalizada).</li>
</ul>
</div>
<div class="card">
<h2 class="anchored">
Calidad de los Datos
</h2>
<p>El numero de filas con los que se encuentra el dataset en crudo son de 89,720 registros de los cuales posiblemente existan filas con valores incompletos, o bien, existan columnas cuyos datos se encuentran nulos, como consecuencia pueden existir inconsistencias en la calidad de los datos.</p>
<p>A continuación se presenta la cantidad y porcentaje de datos faltantes por columna en el dataset de análisis.</p>
<div id="6dc60e92" class="cell" title="Valores faltantes en el dataset" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<style type="text/css">
#T_a2517 th {
  font-weight: 600;
  font-size: 12px;
  border-bottom: 2px solid #ddd;
}
#T_a2517 td {
  padding: 6px 10px;
  border-bottom: 1px solid #eee;
}
#T_a2517_row0_col0, #T_a2517_row0_col1, #T_a2517_row0_col3, #T_a2517_row1_col0, #T_a2517_row1_col1, #T_a2517_row1_col3, #T_a2517_row2_col0, #T_a2517_row2_col1, #T_a2517_row2_col3, #T_a2517_row3_col0, #T_a2517_row3_col1, #T_a2517_row3_col3, #T_a2517_row4_col0, #T_a2517_row4_col1, #T_a2517_row4_col3, #T_a2517_row5_col0, #T_a2517_row5_col1, #T_a2517_row5_col3, #T_a2517_row6_col0, #T_a2517_row6_col1, #T_a2517_row6_col3, #T_a2517_row7_col0, #T_a2517_row7_col1, #T_a2517_row7_col3, #T_a2517_row8_col0, #T_a2517_row8_col1, #T_a2517_row8_col3, #T_a2517_row9_col0, #T_a2517_row9_col1, #T_a2517_row9_col3, #T_a2517_row10_col0, #T_a2517_row10_col1, #T_a2517_row10_col3, #T_a2517_row11_col0, #T_a2517_row11_col1, #T_a2517_row11_col3, #T_a2517_row12_col0, #T_a2517_row12_col1, #T_a2517_row12_col3 {
  font-size: 12px;
  text-align: left;
}
#T_a2517_row0_col2, #T_a2517_row1_col2, #T_a2517_row2_col2, #T_a2517_row3_col2, #T_a2517_row4_col2, #T_a2517_row5_col2, #T_a2517_row6_col2, #T_a2517_row7_col2, #T_a2517_row9_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fff5f0;
  color: #000000;
}
#T_a2517_row8_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #67000d;
  color: #f1f1f1;
}
#T_a2517_row10_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #7e0610;
  color: #f1f1f1;
}
#T_a2517_row11_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fc997a;
  color: #000000;
}
#T_a2517_row12_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fcbba1;
  color: #000000;
}
</style>

<table id="T_a2517" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_a2517_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Columna</th>
<th id="T_a2517_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Valores faltantes</th>
<th id="T_a2517_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Porcentaje (%)</th>
<th id="T_a2517_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Tipo inferido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_a2517_row0_col0" class="data row0 col0">Unnamed: 0</td>
<td id="T_a2517_row0_col1" class="data row0 col1">0</td>
<td id="T_a2517_row0_col2" class="data row0 col2">0.000000</td>
<td id="T_a2517_row0_col3" class="data row0 col3">int64</td>
</tr>
<tr class="even">
<td id="T_a2517_row1_col0" class="data row1 col0">nombrecompleto</td>
<td id="T_a2517_row1_col1" class="data row1 col1">0</td>
<td id="T_a2517_row1_col2" class="data row1 col2">0.000000</td>
<td id="T_a2517_row1_col3" class="data row1 col3">str</td>
</tr>
<tr class="odd">
<td id="T_a2517_row2_col0" class="data row2 col0">rnpdno_json</td>
<td id="T_a2517_row2_col1" class="data row2 col1">0</td>
<td id="T_a2517_row2_col2" class="data row2 col2">0.000000</td>
<td id="T_a2517_row2_col3" class="data row2 col3">int64</td>
</tr>
<tr class="even">
<td id="T_a2517_row3_col0" class="data row3 col0">entidad_desap</td>
<td id="T_a2517_row3_col1" class="data row3 col1">0</td>
<td id="T_a2517_row3_col2" class="data row3 col2">0.000000</td>
<td id="T_a2517_row3_col3" class="data row3 col3">str</td>
</tr>
<tr class="odd">
<td id="T_a2517_row4_col0" class="data row4 col0">pre_rnped</td>
<td id="T_a2517_row4_col1" class="data row4 col1">0</td>
<td id="T_a2517_row4_col2" class="data row4 col2">0.000000</td>
<td id="T_a2517_row4_col3" class="data row4 col3">int64</td>
</tr>
<tr class="even">
<td id="T_a2517_row5_col0" class="data row5 col0">rnped</td>
<td id="T_a2517_row5_col1" class="data row5 col1">0</td>
<td id="T_a2517_row5_col2" class="data row5 col2">0.000000</td>
<td id="T_a2517_row5_col3" class="data row5 col3">int64</td>
</tr>
<tr class="odd">
<td id="T_a2517_row6_col0" class="data row6 col0">rnpdno_csv</td>
<td id="T_a2517_row6_col1" class="data row6 col1">0</td>
<td id="T_a2517_row6_col2" class="data row6 col2">0.000000</td>
<td id="T_a2517_row6_col3" class="data row6 col3">int64</td>
</tr>
<tr class="even">
<td id="T_a2517_row7_col0" class="data row7 col0">bg_1</td>
<td id="T_a2517_row7_col1" class="data row7 col1">0</td>
<td id="T_a2517_row7_col2" class="data row7 col2">0.000000</td>
<td id="T_a2517_row7_col3" class="data row7 col3">int64</td>
</tr>
<tr class="odd">
<td id="T_a2517_row8_col0" class="data row8 col0">estatus_busqueda</td>
<td id="T_a2517_row8_col1" class="data row8 col1">27364</td>
<td id="T_a2517_row8_col2" class="data row8 col2">30.500000</td>
<td id="T_a2517_row8_col3" class="data row8 col3">str</td>
</tr>
<tr class="even">
<td id="T_a2517_row9_col0" class="data row9 col0">bg_2</td>
<td id="T_a2517_row9_col1" class="data row9 col1">0</td>
<td id="T_a2517_row9_col2" class="data row9 col2">0.000000</td>
<td id="T_a2517_row9_col3" class="data row9 col3">int64</td>
</tr>
<tr class="odd">
<td id="T_a2517_row10_col0" class="data row10 col0">fub</td>
<td id="T_a2517_row10_col1" class="data row10 col1">26050</td>
<td id="T_a2517_row10_col2" class="data row10 col2">29.030000</td>
<td id="T_a2517_row10_col3" class="data row10 col3">str</td>
</tr>
<tr class="even">
<td id="T_a2517_row11_col0" class="data row11 col0">DC_id</td>
<td id="T_a2517_row11_col1" class="data row11 col1">9651</td>
<td id="T_a2517_row11_col2" class="data row11 col2">10.760000</td>
<td id="T_a2517_row11_col3" class="data row11 col3">str</td>
</tr>
<tr class="odd">
<td id="T_a2517_row12_col0" class="data row12 col0">fecha_desap</td>
<td id="T_a2517_row12_col1" class="data row12 col1">6925</td>
<td id="T_a2517_row12_col2" class="data row12 col2">7.720000</td>
<td id="T_a2517_row12_col3" class="data row12 col3">str</td>
</tr>
</tbody>
</table>
</div>
</div>
<h3 class="anchored">
Observaciones
</h3>
<ul>
<li>Se cuenta con 4 columnas que tienen datos faltantes en distintas proporciones, estos corresponden al estatus de búsqueda, Folio Único de Búsqueda, el id técnico DC_id y la fecha de desaparición. Los motivos de tales inconsistencias son variados; sin embargo, hay que constatar que para este punto no estamos considerando el dataset limpio. Aun así, tales motivos son tomados en cuenta en las siguientes secciones.</li>
<li>Columnas como rnpdno_json, rnpdno_csv, pre_rnped, rnped, bg_1 y bg_2 están almacenadas como enteros (0/1) pero representan valores booleanos que indican el estado del registro de la persona, es importante evitar que sean tratadas como variables numéricas continuas en el análisis.</li>
<li>Para la fecha de desaparición registrada se maneja como una cadena, por lo que durante el análisis puede generar complicaciones.</li>
<li>Durante la observación de los registros la columna DC_id contiene identificadores compuestos con texto y múltiples valores concatenados (por ejemplo, “349 (json), 448 (csv), UUID (fub)”), lo que la hace no directamente analizable como variable numérica o categórica simple. Su utilidad es técnica y de trazabilidad, no analítica.</li>
</ul>
</div>
<div class="card">
<h2 class="anchored">
Hipótesis Preliminares
</h2>
<p>A partir de la exploración inicial del dataset se planetan las siguientes hipótesis preliminares como guía para las siguientes etapas.</p>
<ul>
<li>Debido al cambio de registro de RNPED a RNPDNO, se puede sugerir que antes de esta transición los registros eran menos frecuentes debido a que RNPED era menos sitemático y con inconsistencias, introduciendo un sesgo en la información real de las desapariciones ocurridas en los periodos anteriores.</li>
<li>Respecto al porcentaje de valores faltanes en la columna correspondiente al FUB probablemente presenten también mayor proporción de valores faltantes en otras columnas, sugiriendo que son registros con menor información disponible en el sistema.</li>
<li>Debido a la presencia de información sobre la Búsqueda Generalizada en los registros, se debe observar mayor consistencia en el registro del estatus de búsqueda para aquellos registros que se contemplan dentro de la Búsqueda Generalizada (columnas bg_1 y bg_2). Esto debe indicar que estos procedimientos para encontrar a las personas desaparecidas proporcionan información sobre el estatus real de la persona y su registro sea actualizado y consistente.</li>
<li>Con la observación de las fechas de desaparición se espera observar cómo ha progresado la desaparición de personas en México a lo largo del tiempo, de cómo han influido el cambio de RNPED a RNPDNO, la implementación de la Búsqueda Generalizada y otros planes de acción para esta problemática en nuestro país.</li>
</ul>
</div>
</div>
</section>
<section id="preparación-de-datos" class="level3">
<h3 class="anchored">Preparación de Datos</h3>
<p>La siguiente etapa consiste en la limpieza y transformación de los datos. En el contexto este dataset sobre personas desaparecidas en México, cada decisión de limpieza tiene implicaciones directas sobre la representación de casos reales. Limpiar este dataset significa, en términos concretos, asegurarse de que cada fila represente fidedignamente a una persona, sin distorsionar ni invisibilizar ningún caso.</p>
<h2 class="anchored" data-anchor-id="preparación-de-datos">
Tareas de Limpieza
</h2>
<p>Existen múltiples tareas de limpieza que se deben aplicar al dataset, iniciando por el tratamiento de valores faltantes en las múltiples columnas. Es importante analizar cómo impacta la ausencia de dicha variable en el registro de una persona desaparecida y tomar una decisión al respecto, para ello la eliminación de registros o sustitución de valores debe ser realizado con mucho cuidado, pues introducir datos que no existen puede llevar a conclusiones falsas sobre cuándo ocurrieron las desapariciones, afectando potencialmente decisiones de política pública. Tal es el caso de la columna de estatus de búsqueda, eliminar los datos significa crear un sesgo para aquellos casos que no tienen un seguimiento registrado en el sistema.</p>
<p>Otro punto importante a realizar en esta etapa corresponde a la homologación de los datos, por ejemplo, los datos nulos del dataset se pueden considerar como: ““,”NA”, “N/A”, u otros, lo que genera una desnormalización del manejo de datos. Tomar una decisión para tener datos consistentes en este aspecto es fundamental.</p>
<p>Asimismo, la identificación de datos duplicados nos previene de sesgos en la información que a su vez afecta el cálculo de las medidas estadísticas que serán aplicadas. Otro aspecto es la validación de datos correctos, cómo las fechas o valores inconsistentes sobre entidades federativas.</p>
<h2 class="anchored">
Tareas de Transformación
</h2>
<p>Las columnas originales del dataset fueron diseñadas para el registro administrativo, no para el análisis estadístico. Por eso la transformación tiene un papel central en esta etapa. Esto lo podemos identificar con la fecha de desaparición, convertir el dato a formato datetime no es solo un requisito técnico, sino que permite responder preguntas como: ¿en qué año se concentran más desapariciones?, ¿hay meses con mayor incidencia?, ¿cuánto tiempo lleva desaparecida cada persona sin ser localizada?</p>
<p>De igual forma, convertir las columnas booleanas como bg_1, bg_2 y rnpdno_csv a su tipo correcto evita que el análisis las interprete como si tuvieran magnitud numérica. Un promedio de bg_2 podría interpretarse como una proporción de cobertura de la Búsqueda Generalizada, pero solo si se entiende su naturaleza binaria y no como una variable continua.</p>
<h2 class="anchored">
Selección y Creación de Variables
</h2>
<p>El dataset contiene columnas de trazabilidad técnica como DC_id, rnpdno_json, pre_rnped y rnped que fueron útiles para la construcción y cruce de las distintas versiones del registro nacional, pero que pueden no aportar valor al análisis exploratorio sobre el fenómeno de las desapariciones en sí. Excluirlas no significa que sean irrelevantes en términos institucionales, significa que para las preguntas de análisis planteadas en este proyecto, el foco debe estar en las variables que describen a la persona, el lugar, el tiempo y el estatus de búsqueda. Sin embargo, al analizar los datos deberá decidirse cuáles variables son importantes para las preguntas, si podemos obtener información sobre el impacto de la transición de los registros, entonces son variables que también se deben considerar.</p>
<p>Las variables que no existen en el dataset original pero que se pueden construir a partir de él representan uno de los aportes más importantes de esta etapa. Saber el año o el mes de la desaparición, la década a la que pertenece el caso, cuántos años lleva la persona desaparecida sin ser localizada, o si su caso tiene un folio único asignado, son dimensiones que el dataset no entrega directamente pero que son fundamentales para entender la magnitud y evolución del problema.</p>
<p>Por ejemplo, una variable que indique los años que lleva desaparecida una persona (calculada como la diferencia entre la fecha de desaparición y la fecha actual) permite dimensionar la cronicidad de los casos. Un caso con 15 o 20 años sin resolución no es estadísticamente equivalente a uno de hace seis meses, aunque ambos aparezcan como una sola fila en el registro.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Limitaciones">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Limitaciones
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es importante reconocer que la limpieza de datos no corrige el subregistro estructural del fenómeno. Este dataset contiene únicamente los casos que fueron denunciados y registrados formalmente. Las personas desaparecidas cuyos casos nunca llegaron al sistema institucional no aparecen en ninguna fila, y ninguna técnica de preparación de datos puede compensar esa ausencia. Esta limitación debe mantenerse presente a lo largo de todo el análisis como parte de la interpretación honesta de los hallazgos.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Nota">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>La limpieza del dataset se despliega con mayor detalle en <a href="#pestaña-limpieza">Documentación: Limpieza del dataset</a></p>
</div>
</div>
</section>
<section id="modelado" class="level3">
<h3 class="anchored" data-anchor-id="modelado">Modelado</h3>
<p>La fase de modelado se centra en seleccionar y aplicar diversas técnicas de minería de datos, calibrar sus parámetros y construir modelos predictivos o descriptivos. Sin embargo, en el contexto de este proyecto sobre personas desaparecidas en México, aplicar esta etapa adquiere un significado particular y requiere una aproximación ética y analítica muy específica.</p>
<p>El objetivo del modelado aquí es descubrir patrones ocultos, reglas implícitas y anomalías sistemáticas en la forma en que las autoridades han registrado, clasificado, transferido u omitido la información de las víctimas a lo largo del tiempo (especialmente en la transición del RNPED al RNPDNO y durante las fases de Búsqueda Generalizada bg_1 y bg_2). Se busca modelar el proceso de registro y reclasificación, no el delito en sí.</p>
<p>Aunque para los fines de este proyecto no se entrenarán modelos analíticos complejos, las siguientes técnicas de minería de datos serían las más adecuadas para extraer conocimiento profundo de este conjunto de datos.</p>
<h3 class="anchored">
Minería de Reglas de Asociación
</h3>
<p>Esta técnica no supervisada es ideal para descubrir relaciones concurrentes entre variables categóricas y banderas lógicas que a simple vista parecen independientes.</p>
<p>Permitiría descubrir reglas de negocio no documentadas. Por ejemplo, el algoritmo podría encontrar una regla fuerte que indique: SI (rnped == 1) Y (entidad_desap == “VERACRUZ”) Y (bg_1 == 0) ENTONCES (rnpdno_csv == 0). Esto evidenciaría algorítmicamente que los registros históricos de un estado en particular fueron sistemáticamente excluidos de la base pública actual si no entraron en la primera fase de la Búsqueda Generalizada.</p>
<h3 class="anchored">
Algoritmos de Agrupamiento
</h3>
<p>En estas técnicas, al tener variables categóricas, permiten agrupar registros que comparten características muy similares sin necesidad de tener una variable objetivo predefinida.</p>
<p>Podría aplicarse a las variables geográficas (entidad_desap) y temporales (fecha_desap) junto con las banderas de borrado institucional (pre_rnped == 1 y rnpdno_csv == 0). Esto ayudaría a identificar patrones de omición; es decir, espacios temporales en estados específicos donde ocurrieron desapariciones que posteriormente fueron borradas de los registros oficiales de manera masiva, sugiriendo patrones de ocultamiento de información en periodos políticos o de seguridad específicos.</p>
</section>
<section id="evaluación" class="level3">
<h3 class="anchored">Evaluación</h3>
<p>En esta etapa es importante validar hallazgos, identificar sesgos y limitaciones. Básicamente se trata de identificar si el modelo cumple con los objetivos del negocio.</p>
<p>Dado el contexto del presente trabajo respecto a las desapariciones de personas en México, la evaluación consiste en asegurar la validez del conocimiento extraído a partir del conjunto de datos trabajado, reconocer críticamente las deficiencias inherentes de los datos y determinar el valor práctico de los hallazgos para la comprensión del fenómeno.</p>
<h2 class="anchored" data-anchor-id="evaluación">
Validación de Hallazgos
</h2>
<p>Recordando que el objetivo de este trabajo es obtener información sobre las desapariciones en México respecto a las entidades donde ocurren, las fechas de los hechos, los estatus y cómo ha ido progresando a lo largo del tiempo, validar los hallazgos resulta en contrastar los patrones estadísticos descubiertos con el contexto sociopolítico de nuestro país.</p>
<p>Una parte fundamental de la validación de hallazgos se enfoca en el cuidado de manejo de datos durante la limpieza y transformación de los mismos. Durante la etapa de preparación de datos se debe vigilar que no se introduzcan datos inválidos o sesgos debido a datos faltantes. Esto previene errores de interpretación sobre la información analizada.</p>
<p>Asimismo, para validar nuestros hallazgos buscamos responder a las preguntas objetivo planteadas en la parte de comprensión del negocio, esto nos permite enfocar el análisis de los datos a planteamientos específicos y así poder realizar conclusiones a partir de las observaciones. Otro aspecto a considerar en la evaluación es comparar los resultados de las medidas de los datos con las hipótesis preliminares antes planteadas para poder reforzarlas o refutarlas, de este modo podemos generar nuevas hipótesis y descubrir nuevos enfoques que no se consideraron al inicio de la metodología.</p>
<h2 class="anchored">
Sesgos y Limitaciones
</h2>
<p>Dado que el conjunto de datos que se trabaja es únicamente sobre registros oficiales ante autoridades administrativas, existen limitaciones sobre las cifras reales de las desapariciones de personas en México. Para que una persona desaparecida o no localizada sea considerada en este análisis, debe haber sido reportado ante las autoridades con el debido proceso. Esto resulta en que los hallazgos obtenidos a partir de la información no dimensionan verdaderamente la crisis en México, pero si ofrece un acercamiento al respecto.</p>
<p>Por otro lado, como se pudo observar en la exploración inicial de los datos se identifico falta de información de múltiples registros en datos esenciales como el estatus de búsqueda o la fecha de desaparición. La alta prevalencia de datos faltantes restringe la profundidad de ciertos análisis temporales y espaciales, obligando a descartar filas que podrían contener información valiosa. Es por ello que en la limpieza del dataset se justifica cada decisión tomada al respecto para tener el mejor análisis posible.</p>
<p>Además, los datos son generados, administrados y modificados por entidades gubernamentales que responden a métricas y presiones políticas. Variables clave como el estatus_busqueda o la inclusión en la Búsqueda Generalizada (bg_1, bg_2) pueden reflejar decisiones administrativas diseñadas para disminuir estadísticamente el número de casos activos, lo que introduce un sesgo oficialista en el análisis.</p>
<p>Así, el análisis será útil si proporciona evidencia cuantitativa, reproducible y estructurada sobre las inconsistencias del registro, transformando un archivo CSV complejo en métricas claras de omisión y trazabilidad.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un criterio de utilidad innegociable es el respeto irrestricto a los datos sensibles. El análisis no debe revictimizar a las personas ni a sus familias, garantizando que el tratamiento de la información (nombres, fechas y estatus) se utilice exclusivamente para dimensionar la crisis en México sobre desapariciones de personas mediante la obtención de patrones en la información.</p>
</div>
</div>
</section>
<section id="despliegue" class="level3">
<h3 class="anchored" data-anchor-id="despliegue">Despliegue</h3>
<p>En el marco de este proyecto enfocado en la crisis de personas desaparecidas en México y la trazabilidad de los registros gubernamentales, la fase de despliegue no contempla la implementación de un software en tiempo real, sino la democratización, documentación y presentación estratégica de los hallazgos. El objetivo de esta fase es garantizar que el análisis sea reproducible, auditable y, sobre todo, comprensible para la toma de decisiones.</p>
<p>Como resultado se realiza un reporte con el desarrollo y resultados de todo el proceso de la información que va desde la comprensión de la problemática hasta la presentación de hallazgos con sustento cuantitativo y herramientas de visualización que permitan comunicar el análisis llevado a cabo, y el dataset limpio y transformado con las debidas justificaciones de las decisiones tomada al respecto.</p>
</section>
</section>
</section>
<section id="pestaña-limpieza" class="level1">
<h1>Documentación: Limpieza del dataset</h1>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La calidad y confiabilidad de los resultados en cualquier proyecto de minería de datos dependen directamente de la integridad y estructura del conjunto de datos original. En el contexto de los registros oficiales de personas desaparecidas en México (RNPED y RNPDNO), el dataset en su formato crudo presenta múltiples desafíos técnicos inherentes a su captura administrativa y origen gubernamental. Entre estos retos destacan la presencia de inconsistencias tipográficas, formatos de fecha anómalos o múltiples, una alta prevalencia de valores nulos no estandarizados y variables de trazabilidad codificadas con tipos de datos incorrectos.</p>
<p>El objetivo de esta fase de limpieza y preparación es transformar la base de datos original sin alterar la realidad histórica que representan los registros. A continuación, se documentan de manera transparente y detallada todas las decisiones técnicas aplicadas al dataset. Este proceso asegura la reproducibilidad del análisis y abarca el tratamiento de valores faltantes, la revisión de duplicados, la corrección de tipos de datos, la normalización de categorías y la validación rigurosa de inconsistencias lógicas.</p>
</section>
<section id="documentación" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="documentación">Documentación</h2>
<section id="normalización" class="level3">
<h3 class="anchored" data-anchor-id="normalización">Normalización</h3>
<div class="card">
<p>La normalización es el proceso técnico de estandarizar, corregir y unificar los valores de texto y las variables categóricas dentro del dataset. La normalización de categorías tuvo como objetivo garantizar que valores que representan el mismo concepto sean reconocidos como idénticos por pandas, evitando que diferencias superficiales de formato generen categorías duplicadas en el análisis. Por otro lado, la normalización de texto nos permite más legibilidad y confiabilidad en los datos.</p>
<p>Para un algoritmo o función de agrupación en Pandas, cualquier ligera variación (un espacio extra, un acento, una letra minúscula) hace que el dato sea interpretado como una categoría completamente diferente. Esto fragmentaría los resultados y arruinaría cualquier análisis estadístico. A continuación de detallan las acciones tomadas para cubrir este aspecto.</p>
</div>
<div class="card">
<h3 class="anchored">
Nombres de personas en el registro
</h3>
<p>Se aplicaron tres transformaciones: conversión a mayúsculas, eliminación de espacios al inicio y al final, y colapso de espacios internos múltiples en un único espacio.</p>
<div id="c73dcbaa" class="cell" title="Normalización de nombres" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'nombrecompleto'</span>] <span class="op">=</span> df[<span class="st">'nombrecompleto'</span>].<span class="bu">str</span>.upper().<span class="bu">str</span>.strip()</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'nombrecompleto'</span>] <span class="op">=</span> df[<span class="st">'nombrecompleto'</span>].<span class="bu">str</span>.replace(<span class="vs">r'</span><span class="dv">\s</span><span class="op">+</span><span class="vs">'</span>, <span class="st">' '</span>, regex<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Entidades federativas
</h3>
<p>Además de la conversión a mayúsculas y la eliminación de espacios, se aplicó una normalización de caracteres Unicode para eliminar acentos. El resultado es que “QUERÉTARO” y “QUERETARO” quedan representados de forma idéntica, evitando que aparezcan como dos entidades distintas en el análisis.</p>
<div id="e9f8879f" class="cell" title="Normalización de entidades" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> df[<span class="st">'entidad_desap'</span>].<span class="bu">str</span>.upper().<span class="bu">str</span>.strip()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> (</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'entidad_desap'</span>]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.normalize(<span class="st">'NFKD'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.encode(<span class="st">'ascii'</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.decode(<span class="st">'utf-8'</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Estatus de búsqueda
</h3>
<p>Para esta columna se optó por capitalización en lugar de mayúsculas completas (es decir, primera letra mayúscula y el resto en minúsculas) dado que los valores de estatus son frases descriptivas y su presentación en mayúsculas completas dificultaría la lectura en tablas y visualizaciones del dashboard. Se aplicó también strip() para eliminar espacios al inicio y al final.</p>
<div id="63ecbe9f" class="cell" title="Normalización de estatus de búsqueda" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].<span class="bu">str</span>.capitalize().<span class="bu">str</span>.strip()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="tipos-de-datos" class="level3">
<h3 class="anchored">Tipos de Datos</h3>
<div data-layout-nrow="6">
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="card quarto-layout-cell" style="flex-basis: 70.0%;justify-content: center;">
<p>Al empezar a trabajar con el dataset original se obtienen los siguientes tipos de datos:</p>
<div id="101c76f3" class="cell" title="Tipos de Datos Iniciales" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<style type="text/css">
#T_fd89c th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_fd89c td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_fd89c_row0_col0, #T_fd89c_row0_col1, #T_fd89c_row1_col0, #T_fd89c_row1_col1, #T_fd89c_row2_col0, #T_fd89c_row2_col1, #T_fd89c_row3_col0, #T_fd89c_row3_col1, #T_fd89c_row4_col0, #T_fd89c_row4_col1, #T_fd89c_row5_col0, #T_fd89c_row5_col1, #T_fd89c_row6_col0, #T_fd89c_row6_col1, #T_fd89c_row7_col0, #T_fd89c_row7_col1, #T_fd89c_row8_col0, #T_fd89c_row8_col1, #T_fd89c_row9_col0, #T_fd89c_row9_col1, #T_fd89c_row10_col0, #T_fd89c_row10_col1, #T_fd89c_row11_col0, #T_fd89c_row11_col1, #T_fd89c_row12_col0, #T_fd89c_row12_col1 {
  font-size: 12px;
  text-align: left;
}
</style>

<table id="T_fd89c" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_fd89c_level0_col0" class="col_heading level0 col0" style="text-align: left;" data-quarto-table-cell-role="th">Columna</th>
<th id="T_fd89c_level0_col1" class="col_heading level0 col1" style="text-align: left;" data-quarto-table-cell-role="th">Tipo de dato</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_fd89c_row0_col0" class="data row0 col0" style="text-align: left;">Unnamed: 0</td>
<td id="T_fd89c_row0_col1" class="data row0 col1" style="text-align: left;">int64</td>
</tr>
<tr class="even">
<td id="T_fd89c_row1_col0" class="data row1 col0" style="text-align: left;">nombrecompleto</td>
<td id="T_fd89c_row1_col1" class="data row1 col1" style="text-align: left;">str</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row2_col0" class="data row2 col0" style="text-align: left;">rnpdno_json</td>
<td id="T_fd89c_row2_col1" class="data row2 col1" style="text-align: left;">int64</td>
</tr>
<tr class="even">
<td id="T_fd89c_row3_col0" class="data row3 col0" style="text-align: left;">entidad_desap</td>
<td id="T_fd89c_row3_col1" class="data row3 col1" style="text-align: left;">str</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row4_col0" class="data row4 col0" style="text-align: left;">pre_rnped</td>
<td id="T_fd89c_row4_col1" class="data row4 col1" style="text-align: left;">int64</td>
</tr>
<tr class="even">
<td id="T_fd89c_row5_col0" class="data row5 col0" style="text-align: left;">rnped</td>
<td id="T_fd89c_row5_col1" class="data row5 col1" style="text-align: left;">int64</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row6_col0" class="data row6 col0" style="text-align: left;">rnpdno_csv</td>
<td id="T_fd89c_row6_col1" class="data row6 col1" style="text-align: left;">int64</td>
</tr>
<tr class="even">
<td id="T_fd89c_row7_col0" class="data row7 col0" style="text-align: left;">bg_1</td>
<td id="T_fd89c_row7_col1" class="data row7 col1" style="text-align: left;">int64</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row8_col0" class="data row8 col0" style="text-align: left;">estatus_busqueda</td>
<td id="T_fd89c_row8_col1" class="data row8 col1" style="text-align: left;">str</td>
</tr>
<tr class="even">
<td id="T_fd89c_row9_col0" class="data row9 col0" style="text-align: left;">bg_2</td>
<td id="T_fd89c_row9_col1" class="data row9 col1" style="text-align: left;">int64</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row10_col0" class="data row10 col0" style="text-align: left;">fub</td>
<td id="T_fd89c_row10_col1" class="data row10 col1" style="text-align: left;">str</td>
</tr>
<tr class="even">
<td id="T_fd89c_row11_col0" class="data row11 col0" style="text-align: left;">DC_id</td>
<td id="T_fd89c_row11_col1" class="data row11 col1" style="text-align: left;">str</td>
</tr>
<tr class="odd">
<td id="T_fd89c_row12_col0" class="data row12 col0" style="text-align: left;">fecha_desap</td>
<td id="T_fd89c_row12_col1" class="data row12 col1" style="text-align: left;">str</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="card quarto-layout-cell" style="flex-basis: 30.0%;justify-content: flex-start;">
<p>Una vez cargado el dataset, pandas infiere automáticamente los tipos de datos de cada columna. Sin embargo, esta inferencia no siempre refleja la naturaleza real de los datos. Es por esto que se realizaron conversiones explícitas antes de cualquier análisis. Al realizar la exploración inicial de los datos en la etapa de Comprensión de los Datos en CRISP-DM observamos ciertas inconsistencias que dificultan el proceso de la información. A continuación se presentan los cambios realizados al dataset.</p>
</div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Variables Booleanas
</h3>
<p>Las columnas rnpdno_json, pre_rnped, rnped, rnpdno_csv, bg_1 y bg_2 fueron cargadas como int64 con valores 0 y 1 (su interpretación se presenta en el diccionario en <a href="#crisp-dm">Comprensión de los Datos</a>). Aunque numéricamente son equivalentes, tratarlas como enteros permitiría operaciones sin sentido sobre ellas, como calcular su promedio o aplicarles transformaciones aritméticas. Al convertirlas a tipo bool se establece explícitamente que representan una condición binaria, lo que restringe las operaciones válidas sobre ellas y comunica correctamente su significado dentro del dataset.</p>
<div id="0f90a344" class="cell" title="Transformación valores booleanos" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>columnas_booleanas <span class="op">=</span> [<span class="st">'rnpdno_json'</span>, <span class="st">'pre_rnped'</span>, <span class="st">'rnped'</span>, <span class="st">'rnpdno_csv'</span>, <span class="st">'bg_1'</span>, <span class="st">'bg_2'</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> columnas_booleanas:</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].astype(<span class="bu">bool</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Variables con Texto
</h3>
<p>Las columnas nombrecompleto, fub y DC_id fueron convertidas al tipo string de pandas, distinto del tipo genérico object. Esta distinción es relevante porque el tipo string maneja los valores nulos como pd.NA en lugar de None o NaN, lo que hace más predecible y consistente el comportamiento al operar con texto y al detectar ausencias en estas columnas.</p>
<div id="e334bd76" class="cell" title="Transformación a tipo string" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>columnas_texto <span class="op">=</span> [<span class="st">'nombrecompleto'</span>, <span class="st">'fub'</span>, <span class="st">'DC_id'</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> columnas_texto:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].astype(<span class="st">'string'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Variables de Fecha
</h3>
<p>Para la columna fecha_desap se cargo como cadena de texto, durante la revisión de los datos se encontraron registros con la presencia de múltiples fechas separadas por comas, además de valores nulos o formatos inconsistentes.</p>
<ol type="1">
<li>Debido a la presencia de cadenas con múltiples fechas registradas, se decidió extraer únicamente la primera fecha registrada, pues si a ese registro le asignan un folio FUB debe ser con la primera fecha registrada. Con esto, en lugar de eliminar el dato a nulo, obtenemos un acercamiento con la primera fecha registrada.</li>
<li>Se homologaron todas las representaciones posibles de datos nulos a np.nan.</li>
<li>Por último, se aplica la conversión a datetime64 y cualquier valor que no pueda interpretarse como fecha válida se transforma a valor nulo.</li>
</ol>
<div id="d7dc1134" class="cell" title="Transformación a tipo datetime" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].<span class="bu">str</span>.split(<span class="st">','</span>).<span class="bu">str</span>[<span class="dv">0</span>].<span class="bu">str</span>.strip()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].replace({</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NA'</span>: np.nan, <span class="st">'nan'</span>: np.nan, <span class="st">'&lt;NA&gt;'</span>: np.nan, <span class="st">'None'</span>: np.nan, <span class="st">''</span>: np.nan</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'fecha_desap'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'mixed'</span>, dayfirst<span class="op">=</span><span class="va">True</span>, errors<span class="op">=</span><span class="st">'coerce'</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Variables Categóricas
</h3>
<p>Columnas como entidad_desap o estatus_busqueda aparecen inicialmente como un tipo de dato de cadena de texto, por lo que dado su significado resulta conveniente convertirlos a un tipo category no sin antes normalizar su contenido como se menciona en la sección correspondiente.</p>
<p>Esta conversión es apropiada porque ambas columnas tienen un número reducido y finito de valores posibles (los estados de la república y los estatus de búsqueda definidos) y no representan texto libre. El tipo category reduce el uso de memoria significativamente en datasets grandes y permite operaciones de agrupación más eficientes. Es importante destacar que esta conversión se realizó después de la normalización de texto, para garantizar que las categorías registradas sean uniformes y no existan duplicados implícitos por diferencias de capitalización o espacios.</p>
<div id="d47a58bf" class="cell" title="Transformación a tipo category" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> df[<span class="st">'entidad_desap'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].astype(<span class="st">'category'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<h2 class="anchored" data-anchor-id="tipos-de-datos">
Resultado
</h2>
<div id="3ef15b7c" class="cell" title="Tipos de Datos Finales" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="13">
<style type="text/css">
#T_13b30 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_13b30 td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_13b30_row0_col0, #T_13b30_row0_col1, #T_13b30_row1_col0, #T_13b30_row1_col1, #T_13b30_row2_col0, #T_13b30_row2_col1, #T_13b30_row3_col0, #T_13b30_row3_col1, #T_13b30_row4_col0, #T_13b30_row4_col1, #T_13b30_row5_col0, #T_13b30_row5_col1, #T_13b30_row6_col0, #T_13b30_row6_col1, #T_13b30_row7_col0, #T_13b30_row7_col1, #T_13b30_row8_col0, #T_13b30_row8_col1, #T_13b30_row9_col0, #T_13b30_row9_col1, #T_13b30_row10_col0, #T_13b30_row10_col1, #T_13b30_row11_col0, #T_13b30_row11_col1, #T_13b30_row12_col0, #T_13b30_row12_col1 {
  font-size: 12px;
  text-align: left;
}
</style>

<table id="T_13b30" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_13b30_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Columna</th>
<th id="T_13b30_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Tipo de dato</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_13b30_row0_col0" class="data row0 col0">Unnamed: 0</td>
<td id="T_13b30_row0_col1" class="data row0 col1">int64</td>
</tr>
<tr class="even">
<td id="T_13b30_row1_col0" class="data row1 col0">nombrecompleto</td>
<td id="T_13b30_row1_col1" class="data row1 col1">string</td>
</tr>
<tr class="odd">
<td id="T_13b30_row2_col0" class="data row2 col0">rnpdno_json</td>
<td id="T_13b30_row2_col1" class="data row2 col1">bool</td>
</tr>
<tr class="even">
<td id="T_13b30_row3_col0" class="data row3 col0">entidad_desap</td>
<td id="T_13b30_row3_col1" class="data row3 col1">category</td>
</tr>
<tr class="odd">
<td id="T_13b30_row4_col0" class="data row4 col0">pre_rnped</td>
<td id="T_13b30_row4_col1" class="data row4 col1">bool</td>
</tr>
<tr class="even">
<td id="T_13b30_row5_col0" class="data row5 col0">rnped</td>
<td id="T_13b30_row5_col1" class="data row5 col1">bool</td>
</tr>
<tr class="odd">
<td id="T_13b30_row6_col0" class="data row6 col0">rnpdno_csv</td>
<td id="T_13b30_row6_col1" class="data row6 col1">bool</td>
</tr>
<tr class="even">
<td id="T_13b30_row7_col0" class="data row7 col0">bg_1</td>
<td id="T_13b30_row7_col1" class="data row7 col1">bool</td>
</tr>
<tr class="odd">
<td id="T_13b30_row8_col0" class="data row8 col0">estatus_busqueda</td>
<td id="T_13b30_row8_col1" class="data row8 col1">category</td>
</tr>
<tr class="even">
<td id="T_13b30_row9_col0" class="data row9 col0">bg_2</td>
<td id="T_13b30_row9_col1" class="data row9 col1">bool</td>
</tr>
<tr class="odd">
<td id="T_13b30_row10_col0" class="data row10 col0">fub</td>
<td id="T_13b30_row10_col1" class="data row10 col1">string</td>
</tr>
<tr class="even">
<td id="T_13b30_row11_col0" class="data row11 col0">DC_id</td>
<td id="T_13b30_row11_col1" class="data row11 col1">string</td>
</tr>
<tr class="odd">
<td id="T_13b30_row12_col0" class="data row12 col0">fecha_desap</td>
<td id="T_13b30_row12_col1" class="data row12 col1">datetime64[us]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</section>
<section id="valores-faltantes" class="level3">
<h3 class="anchored">Valores Faltantes</h3>
<div class="{.layout-nrow=5}">
<div class="card">
<p>A partir de las variables observadas en el dataset, como se menciono en la Comprensión de Datos de la metodología CRISP-DM, existen columnas con datos faltantes. Antes de tomar cualquier decisión sobre estos datos, es importante conocer la proporción de estos con respecto al total de los registros. Es importante mencionar que no todas las ausencias tienen el mismo origen ni la misma solución, en el contexto de las desapariciones de personas en México, un valor faltante puede significar desde un error de captura hasta una limitación en el sistema de registro. En ambos casos, es importante detallar las decisiones para no generar sesgos en la información.</p>
<div id="ba170821" class="cell" title="Valores Faltantes" data-execution_count="14">
<div class="cell-output cell-output-display" data-execution_count="14">
<style type="text/css">
#T_1b8f6 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_1b8f6 td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_1b8f6_row0_col0, #T_1b8f6_row0_col1, #T_1b8f6_row0_col3, #T_1b8f6_row1_col0, #T_1b8f6_row1_col1, #T_1b8f6_row1_col3, #T_1b8f6_row2_col0, #T_1b8f6_row2_col1, #T_1b8f6_row2_col3, #T_1b8f6_row3_col0, #T_1b8f6_row3_col1, #T_1b8f6_row3_col3, #T_1b8f6_row4_col0, #T_1b8f6_row4_col1, #T_1b8f6_row4_col3, #T_1b8f6_row5_col0, #T_1b8f6_row5_col1, #T_1b8f6_row5_col3, #T_1b8f6_row6_col0, #T_1b8f6_row6_col1, #T_1b8f6_row6_col3, #T_1b8f6_row7_col0, #T_1b8f6_row7_col1, #T_1b8f6_row7_col3, #T_1b8f6_row8_col0, #T_1b8f6_row8_col1, #T_1b8f6_row8_col3, #T_1b8f6_row9_col0, #T_1b8f6_row9_col1, #T_1b8f6_row9_col3, #T_1b8f6_row10_col0, #T_1b8f6_row10_col1, #T_1b8f6_row10_col3, #T_1b8f6_row11_col0, #T_1b8f6_row11_col1, #T_1b8f6_row11_col3, #T_1b8f6_row12_col0, #T_1b8f6_row12_col1, #T_1b8f6_row12_col3 {
  font-size: 12px;
  text-align: left;
}
#T_1b8f6_row0_col2, #T_1b8f6_row1_col2, #T_1b8f6_row2_col2, #T_1b8f6_row3_col2, #T_1b8f6_row4_col2, #T_1b8f6_row5_col2, #T_1b8f6_row6_col2, #T_1b8f6_row7_col2, #T_1b8f6_row9_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fff5f0;
  color: #000000;
}
#T_1b8f6_row8_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #67000d;
  color: #f1f1f1;
}
#T_1b8f6_row10_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #7e0610;
  color: #f1f1f1;
}
#T_1b8f6_row11_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fc997a;
  color: #000000;
}
#T_1b8f6_row12_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fcbba1;
  color: #000000;
}
</style>

<table id="T_1b8f6" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_1b8f6_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Columna</th>
<th id="T_1b8f6_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Valores faltantes</th>
<th id="T_1b8f6_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Porcentaje (%)</th>
<th id="T_1b8f6_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Tipo inferido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_1b8f6_row0_col0" class="data row0 col0">Unnamed: 0</td>
<td id="T_1b8f6_row0_col1" class="data row0 col1">0</td>
<td id="T_1b8f6_row0_col2" class="data row0 col2">0.000000</td>
<td id="T_1b8f6_row0_col3" class="data row0 col3">int64</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row1_col0" class="data row1 col0">nombrecompleto</td>
<td id="T_1b8f6_row1_col1" class="data row1 col1">0</td>
<td id="T_1b8f6_row1_col2" class="data row1 col2">0.000000</td>
<td id="T_1b8f6_row1_col3" class="data row1 col3">string</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row2_col0" class="data row2 col0">rnpdno_json</td>
<td id="T_1b8f6_row2_col1" class="data row2 col1">0</td>
<td id="T_1b8f6_row2_col2" class="data row2 col2">0.000000</td>
<td id="T_1b8f6_row2_col3" class="data row2 col3">bool</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row3_col0" class="data row3 col0">entidad_desap</td>
<td id="T_1b8f6_row3_col1" class="data row3 col1">0</td>
<td id="T_1b8f6_row3_col2" class="data row3 col2">0.000000</td>
<td id="T_1b8f6_row3_col3" class="data row3 col3">category</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row4_col0" class="data row4 col0">pre_rnped</td>
<td id="T_1b8f6_row4_col1" class="data row4 col1">0</td>
<td id="T_1b8f6_row4_col2" class="data row4 col2">0.000000</td>
<td id="T_1b8f6_row4_col3" class="data row4 col3">bool</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row5_col0" class="data row5 col0">rnped</td>
<td id="T_1b8f6_row5_col1" class="data row5 col1">0</td>
<td id="T_1b8f6_row5_col2" class="data row5 col2">0.000000</td>
<td id="T_1b8f6_row5_col3" class="data row5 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row6_col0" class="data row6 col0">rnpdno_csv</td>
<td id="T_1b8f6_row6_col1" class="data row6 col1">0</td>
<td id="T_1b8f6_row6_col2" class="data row6 col2">0.000000</td>
<td id="T_1b8f6_row6_col3" class="data row6 col3">bool</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row7_col0" class="data row7 col0">bg_1</td>
<td id="T_1b8f6_row7_col1" class="data row7 col1">0</td>
<td id="T_1b8f6_row7_col2" class="data row7 col2">0.000000</td>
<td id="T_1b8f6_row7_col3" class="data row7 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row8_col0" class="data row8 col0">estatus_busqueda</td>
<td id="T_1b8f6_row8_col1" class="data row8 col1">27364</td>
<td id="T_1b8f6_row8_col2" class="data row8 col2">30.500000</td>
<td id="T_1b8f6_row8_col3" class="data row8 col3">category</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row9_col0" class="data row9 col0">bg_2</td>
<td id="T_1b8f6_row9_col1" class="data row9 col1">0</td>
<td id="T_1b8f6_row9_col2" class="data row9 col2">0.000000</td>
<td id="T_1b8f6_row9_col3" class="data row9 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row10_col0" class="data row10 col0">fub</td>
<td id="T_1b8f6_row10_col1" class="data row10 col1">26050</td>
<td id="T_1b8f6_row10_col2" class="data row10 col2">29.030000</td>
<td id="T_1b8f6_row10_col3" class="data row10 col3">string</td>
</tr>
<tr class="even">
<td id="T_1b8f6_row11_col0" class="data row11 col0">DC_id</td>
<td id="T_1b8f6_row11_col1" class="data row11 col1">9651</td>
<td id="T_1b8f6_row11_col2" class="data row11 col2">10.760000</td>
<td id="T_1b8f6_row11_col3" class="data row11 col3">string</td>
</tr>
<tr class="odd">
<td id="T_1b8f6_row12_col0" class="data row12 col0">fecha_desap</td>
<td id="T_1b8f6_row12_col1" class="data row12 col1">6925</td>
<td id="T_1b8f6_row12_col2" class="data row12 col2">7.720000</td>
<td id="T_1b8f6_row12_col3" class="data row12 col3">datetime64[us]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="card">
<h2 class="anchored" data-anchor-id="valores-faltantes">
Ausencia de estatus de búsqueda
</h2>
<p>La columna estatus_busqueda presentó un total de 27,364 registros nulos, representando el 30.5% del conjunto de datos. Un registro sin estatus representa un reto en la problemática que presenta el país, pues tenemos una pérdida de información del estado de miles de personas desaparecidas.</p>
<p>El estatus de búsqueda de un caso tiene mayor probabilidad de parecerse al de otros casos registrados en la misma entidad federativa, dado que las condiciones institucionales y operativas de búsqueda varían por estado.Es por esto que para el diagnóstico de esta variable se decidió realizar imputación mediante el algoritmo KNN (K-Nearest Neighbors), utilizando la variable correspondiente a la entidad de desaparición como dato auxiliar.</p>
<p>Así, se implementó un algoritmo que identifica los 5 registros más similares en términos de entidad y les asigna el estatus más frecuente entre ellos. Para aplicar KNN fue necesario codificar numéricamente las variables categóricas mediante OrdinalEncoder, ejecutar la imputación y luego decodificar los valores de regreso a sus etiquetas originales.</p>
<div id="d4c40d31" class="cell" title="Algoritmo KNN para estatus de búsqueda" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">'entidad_desap'</span>, <span class="st">'estatus_busqueda'</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df_knn <span class="op">=</span> df[cols].copy()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>encoder <span class="op">=</span> OrdinalEncoder(handle_unknown<span class="op">=</span><span class="st">'use_encoded_value'</span>, unknown_value<span class="op">=</span>np.nan)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> encoder.fit_transform(df_knn)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>imputer <span class="op">=</span> KNNImputer(n_neighbors<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>df_imputed <span class="op">=</span> imputer.fit_transform(df_encoded)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>df_imputed <span class="op">=</span> np.<span class="bu">round</span>(df_imputed)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>df_decoded <span class="op">=</span> encoder.inverse_transform(df_imputed)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df_decoded[:, <span class="dv">1</span>]</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>nulos_estatus <span class="op">=</span> <span class="bu">int</span>(df[<span class="st">'estatus_busqueda'</span>].isnull().<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>De este modo, los nulos tras la aplicación del KNN para el estatus de búsqueda son: <strong>0</strong>.</p>
</div>
<div class="card">
<h2 class="anchored">
Folio Único de Búsqueda y DC_id
</h2>
<p>Dado que estas dos columnas son identificadores técnicos del sistema de registro, su ausencia no puede darnos espacio a imputar con identificadores inventados, pues se introducirían registros falsos en el sistema de trazabilidad y no aportaría ningún valor analítico de acuerdo a los objetivos que se plantearon en este trabajo.</p>
<p>De esta manera, ambas columnas se conservan con sus nulos originales y se excluyen de cualquier análisis estadístico que requiera valores completos.</p>
</div>
<div class="card">
<h2 class="anchored">
Ausencia de Fecha de Desaparición
</h2>
<p>Nuevamente, la ausencia de esta información representa un reto en el análisis de las desapariciones. Esta es una variable central para el análisis temporal del dataset, sin embargo, imputar fechas en un dataset de derechos humanos requiere de especial cuidado, pues asignar fechas arbitrarias a la desaparición de las personas puede distorsionar los patrones temporales y llevar a conclusiones incorrectas sobre los detalles de los hechos.</p>
<p>Con la consideración anterior, se optó por una imputación basada en la moda de fechas dentro de cada entidad federativa. Así, para cada registro con fecha faltante, se identifica la fecha de desaparición más frecuente entre todos los casos del mismo estado y se le asigna un valor.</p>
<div id="a0ddd03f" class="cell" title="Imputación de las fechas de desaparición por moda" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>moda_por_entidad <span class="op">=</span> df.groupby(<span class="st">'entidad_desap'</span>)[<span class="st">'fecha_desap'</span>].transform(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: x.mode()[<span class="dv">0</span>] <span class="cf">if</span> <span class="kw">not</span> x.mode().empty <span class="cf">else</span> pd.NaT</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].fillna(moda_por_entidad)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>nulos_fecha <span class="op">=</span> <span class="bu">int</span>(df[<span class="st">'fecha_desap'</span>].isnull().<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>De este modo, los nulos tras la aplicación de la imputación para la fecha de desaparición son: <strong>0</strong>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>La fecha imputada no representa la fecha real de desaparición de cada persona, sino la fecha más frecuente registrada en su entidad. Esto introduce un sesgo de concentración en ciertas fechas dentro del análisis temporal, por lo que dichos resultados deben interpretarse considerando que un subconjunto de ellos (el 7.7%) tiene fechas aproximadas y no reales.</p>
</div>
</div>
</div>
<div class="card">
<p>Tras aplicar los tratamientos descritos, las únicas columnas que conservan valores nulos son fub y DC_id, cuya ausencia es intencional y justificada.</p>
<div id="c534bb26" class="cell" title="Resultado Valores Faltantes" data-execution_count="17">
<div class="cell-output cell-output-display" data-execution_count="17">
<style type="text/css">
#T_4a160 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_4a160 td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_4a160_row0_col0, #T_4a160_row0_col1, #T_4a160_row0_col3, #T_4a160_row1_col0, #T_4a160_row1_col1, #T_4a160_row1_col3, #T_4a160_row2_col0, #T_4a160_row2_col1, #T_4a160_row2_col3, #T_4a160_row3_col0, #T_4a160_row3_col1, #T_4a160_row3_col3, #T_4a160_row4_col0, #T_4a160_row4_col1, #T_4a160_row4_col3, #T_4a160_row5_col0, #T_4a160_row5_col1, #T_4a160_row5_col3, #T_4a160_row6_col0, #T_4a160_row6_col1, #T_4a160_row6_col3, #T_4a160_row7_col0, #T_4a160_row7_col1, #T_4a160_row7_col3, #T_4a160_row8_col0, #T_4a160_row8_col1, #T_4a160_row8_col3, #T_4a160_row9_col0, #T_4a160_row9_col1, #T_4a160_row9_col3, #T_4a160_row10_col0, #T_4a160_row10_col1, #T_4a160_row10_col3, #T_4a160_row11_col0, #T_4a160_row11_col1, #T_4a160_row11_col3, #T_4a160_row12_col0, #T_4a160_row12_col1, #T_4a160_row12_col3 {
  font-size: 12px;
  text-align: left;
}
#T_4a160_row0_col2, #T_4a160_row1_col2, #T_4a160_row2_col2, #T_4a160_row3_col2, #T_4a160_row4_col2, #T_4a160_row5_col2, #T_4a160_row6_col2, #T_4a160_row7_col2, #T_4a160_row8_col2, #T_4a160_row9_col2, #T_4a160_row12_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fff5f0;
  color: #000000;
}
#T_4a160_row10_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #67000d;
  color: #f1f1f1;
}
#T_4a160_row11_col2 {
  font-size: 12px;
  text-align: left;
  background-color: #fc9474;
  color: #000000;
}
</style>

<table id="T_4a160" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_4a160_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Columna</th>
<th id="T_4a160_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Valores faltantes</th>
<th id="T_4a160_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Porcentaje (%)</th>
<th id="T_4a160_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Tipo inferido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_4a160_row0_col0" class="data row0 col0">Unnamed: 0</td>
<td id="T_4a160_row0_col1" class="data row0 col1">0</td>
<td id="T_4a160_row0_col2" class="data row0 col2">0.000000</td>
<td id="T_4a160_row0_col3" class="data row0 col3">int64</td>
</tr>
<tr class="even">
<td id="T_4a160_row1_col0" class="data row1 col0">nombrecompleto</td>
<td id="T_4a160_row1_col1" class="data row1 col1">0</td>
<td id="T_4a160_row1_col2" class="data row1 col2">0.000000</td>
<td id="T_4a160_row1_col3" class="data row1 col3">string</td>
</tr>
<tr class="odd">
<td id="T_4a160_row2_col0" class="data row2 col0">rnpdno_json</td>
<td id="T_4a160_row2_col1" class="data row2 col1">0</td>
<td id="T_4a160_row2_col2" class="data row2 col2">0.000000</td>
<td id="T_4a160_row2_col3" class="data row2 col3">bool</td>
</tr>
<tr class="even">
<td id="T_4a160_row3_col0" class="data row3 col0">entidad_desap</td>
<td id="T_4a160_row3_col1" class="data row3 col1">0</td>
<td id="T_4a160_row3_col2" class="data row3 col2">0.000000</td>
<td id="T_4a160_row3_col3" class="data row3 col3">category</td>
</tr>
<tr class="odd">
<td id="T_4a160_row4_col0" class="data row4 col0">pre_rnped</td>
<td id="T_4a160_row4_col1" class="data row4 col1">0</td>
<td id="T_4a160_row4_col2" class="data row4 col2">0.000000</td>
<td id="T_4a160_row4_col3" class="data row4 col3">bool</td>
</tr>
<tr class="even">
<td id="T_4a160_row5_col0" class="data row5 col0">rnped</td>
<td id="T_4a160_row5_col1" class="data row5 col1">0</td>
<td id="T_4a160_row5_col2" class="data row5 col2">0.000000</td>
<td id="T_4a160_row5_col3" class="data row5 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_4a160_row6_col0" class="data row6 col0">rnpdno_csv</td>
<td id="T_4a160_row6_col1" class="data row6 col1">0</td>
<td id="T_4a160_row6_col2" class="data row6 col2">0.000000</td>
<td id="T_4a160_row6_col3" class="data row6 col3">bool</td>
</tr>
<tr class="even">
<td id="T_4a160_row7_col0" class="data row7 col0">bg_1</td>
<td id="T_4a160_row7_col1" class="data row7 col1">0</td>
<td id="T_4a160_row7_col2" class="data row7 col2">0.000000</td>
<td id="T_4a160_row7_col3" class="data row7 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_4a160_row8_col0" class="data row8 col0">estatus_busqueda</td>
<td id="T_4a160_row8_col1" class="data row8 col1">0</td>
<td id="T_4a160_row8_col2" class="data row8 col2">0.000000</td>
<td id="T_4a160_row8_col3" class="data row8 col3">category</td>
</tr>
<tr class="even">
<td id="T_4a160_row9_col0" class="data row9 col0">bg_2</td>
<td id="T_4a160_row9_col1" class="data row9 col1">0</td>
<td id="T_4a160_row9_col2" class="data row9 col2">0.000000</td>
<td id="T_4a160_row9_col3" class="data row9 col3">bool</td>
</tr>
<tr class="odd">
<td id="T_4a160_row10_col0" class="data row10 col0">fub</td>
<td id="T_4a160_row10_col1" class="data row10 col1">26050</td>
<td id="T_4a160_row10_col2" class="data row10 col2">29.030000</td>
<td id="T_4a160_row10_col3" class="data row10 col3">string</td>
</tr>
<tr class="even">
<td id="T_4a160_row11_col0" class="data row11 col0">DC_id</td>
<td id="T_4a160_row11_col1" class="data row11 col1">9651</td>
<td id="T_4a160_row11_col2" class="data row11 col2">10.760000</td>
<td id="T_4a160_row11_col3" class="data row11 col3">string</td>
</tr>
<tr class="odd">
<td id="T_4a160_row12_col0" class="data row12 col0">fecha_desap</td>
<td id="T_4a160_row12_col1" class="data row12 col1">0</td>
<td id="T_4a160_row12_col2" class="data row12 col2">0.000000</td>
<td id="T_4a160_row12_col3" class="data row12 col3">datetime64[us]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</section>
<section id="duplicados" class="level3">
<h3 class="anchored" data-anchor-id="duplicados">Duplicados</h3>
<div class="{.layout-nrow=4}">
<div class="card">
<p>Antes de iniciar con la revisión de los duplicados, en el dataset contamos con una columna llamada Unnamed:0, la cual simplemente es un conteo de filas y no es necesario para el análisis, por ello, eliminamos la columna que no nos aporta información.</p>
<div id="f48b5931" class="cell" title="Eliminación de columna Unnamed:0" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'Unnamed: 0'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<p>Para identificar duplicados en el dataset actual además de considerar la existencia de filas completamente idénticas, se identifican registros que con el mismo nombre pueden corresponder a personas distintas, y que eliminar un caso real por considerarlo duplicado tendría implicaciones éticas sensibles.</p>
</div>
<div class="card">
<p>Buscamos filas completamente idénticas en todas las columnas. Un duplicado exacto indica que el mismo registro fue ingresado más de una ve al sistema sin ninguna variación, lo que representa un error de captura o de integración entre las distintas fuentes del dataset. Se eliminan aquellos duplicados sin pérdida de información cuando son totalmente idénticas.</p>
<div id="2f7a78b2" class="cell" title="Detección de duplicados exactos" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cantidades de los duplicados</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>registros_inicial <span class="op">=</span> <span class="bu">len</span>(df)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>duplicados_totales <span class="op">=</span> <span class="bu">int</span>(df.duplicated().<span class="bu">sum</span>())</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="op">=</span> <span class="bu">round</span>(duplicados_totales <span class="op">/</span> registros_inicial <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminación de duplicados</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>df.drop_duplicates(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>registros_finales <span class="op">=</span> df.shape[<span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Número de registros duplicados: <strong>318</strong></p>
<p>Número de registros finales: <strong>89402</strong></p>
<p>Porcentaje de registros eliminados <strong>0.35%</strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>En este dataset cada fila representa a una persona. Eliminar un registro sin certeza de que sea un duplicado equivale a borrar del análisis a una persona real. Por esta razón, solo se eliminan aquellos casos donde la evidencia de duplicidad es inequívoca, es decir, cuando coinciden nombre, fecha de desaparición y folio único de búsqueda simultáneamente.</p>
</div>
</div>
</div>
</div>
</section>
<section id="validaciones" class="level3">
<h3 class="anchored">Validaciones</h3>
<div class="{.layout-nrow=4}">
<div class="card">
<p>En esta sección se busca validar los datos contenidos mediante la revisión y búsqueda de datos anómalos. Se analizan principalmente las fechas y los rangos establecidos para no realizar análisis con valores atípicos erróneos.</p>
</div>
<div class="card">
<h3 class="anchored">
Fecha
</h3>
<p>La fecha de desaparición debe cumplir dos condiciones para ser válida: no puede ser anterior a una fecha mínima razonable y no puede ser posterior a la fecha actual. Se estableció como límite inferior el 1 de enero de 1950, considerando que registros anteriores a esa fecha tendrían más de 75 años de antigüedad y su presencia en un sistema de registro moderno sería altamente sospechosa de error de captura. Los casos fuera de rango se documentan pero no se eliminan automáticamente cada caso requiere revisión individual antes de decidir si se trata de un error de captura o un registro legítimo.</p>
<div id="eed85bfe" class="cell" title="Validación de rangos en fecha_desap" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"fecha_desap"</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">"fecha_desap"</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"mixed"</span>, dayfirst<span class="op">=</span><span class="va">True</span>, errors<span class="op">=</span><span class="st">"coerce"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fecha_min <span class="op">=</span> pd.to_datetime(<span class="st">"1950-01-01"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>fecha_max <span class="op">=</span> pd.to_datetime(dt.date.today())</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>fechas_invalidas <span class="op">=</span> df[</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">"fecha_desap"</span>] <span class="op">&lt;</span> fecha_min) <span class="op">|</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">"fecha_desap"</span>] <span class="op">&gt;</span> fecha_max)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Fechas fuera de rango: </span><span class="sc">{</span><span class="bu">int</span>(<span class="bu">len</span>(fechas_invalidas))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(fechas_invalidas) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    fechas_invalidas[[<span class="st">"nombrecompleto"</span>, <span class="st">"fecha_desap"</span>, <span class="st">"entidad_desap"</span>]] <span class="op">\</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        .reset_index(drop<span class="op">=</span><span class="va">True</span>) <span class="op">\</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        .style <span class="op">\</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        .set_properties(<span class="op">**</span>{<span class="st">"font-size"</span>: <span class="st">"12px"</span>, <span class="st">"text-align"</span>: <span class="st">"left"</span>}) <span class="op">\</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        .set_table_styles([</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"selector"</span>: <span class="st">"th"</span>, <span class="st">"props"</span>: [</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"background-color"</span>, <span class="st">"#4d2c18"</span>), (<span class="st">"color"</span>, <span class="st">"white"</span>),</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"font-weight"</span>, <span class="st">"bold"</span>), (<span class="st">"font-size"</span>, <span class="st">"14px"</span>),</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"text-align"</span>, <span class="st">"left"</span>), (<span class="st">"padding"</span>, <span class="st">"10px"</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>            ]},</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>            {<span class="st">"selector"</span>: <span class="st">"td"</span>, <span class="st">"props"</span>: [</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"padding"</span>, <span class="st">"8px 10px"</span>),</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"border-bottom"</span>, <span class="st">"1px solid #dcb685"</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>            ]},</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"No se encontraron fechas fuera de rango."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fechas fuera de rango: 0
No se encontraron fechas fuera de rango.</code></pre>
</div>
</div>
</div>
<div class="card">
<h3 class="anchored">
Nombres
</h3>
<p>Los nombres de personas no deberían contener caracteres numéricos, símbolos especiales o cadenas que sugieran errores de captura. Se verificaron dos casos: nombres con dígitos y nombres con valores genéricos de relleno como <code>"DESCONOCIDO"</code> o <code>"NN"</code>. Los registros con nombres genéricos como <code>"NN"</code> (no nombrado) son legítimos en este contexto, representan personas no identificadas, y no se eliminan. Se documentan para considerarlos al interpretar resultados sobre nombres o frecuencias.</p>
<div id="a204299e" class="cell" title="Validación de nombres con dígitos" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>nombres_numericos <span class="op">=</span> df[df[<span class="st">"nombrecompleto"</span>].<span class="bu">str</span>.contains(<span class="vs">r'</span><span class="dv">\d</span><span class="vs">'</span>, na<span class="op">=</span><span class="va">False</span>)]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nombres con dígitos: </span><span class="sc">{</span><span class="bu">len</span>(nombres_numericos)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(nombres_numericos) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    display(nombres_numericos[[<span class="st">"nombrecompleto"</span>, <span class="st">"fecha_desap"</span>, <span class="st">"entidad_desap"</span>]].head(<span class="dv">10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombres con dígitos: 5</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nombrecompleto</th>
<th data-quarto-table-cell-role="th">fecha_desap</th>
<th data-quarto-table-cell-role="th">entidad_desap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">870</th>
<td>J0SE AGUIRRE</td>
<td>2013-03-21</td>
<td>CHIHUAHUA</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7311</th>
<td>ARACELI GARCIA AST0RGA</td>
<td>2014-06-09</td>
<td>COAHUILA</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16386</th>
<td>ERIK MARTIN MARTINEZ JIMENEZ080</td>
<td>2017-02-28</td>
<td>NUEVO LEON</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19944</th>
<td>MIGUEL ANEL00 PLACENCIA CORTEZ</td>
<td>2011-12-22</td>
<td>JALISCO</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">28919</th>
<td>ELIMINADO-10 ELIMINADO-11</td>
<td>2007-01-01</td>
<td>SE DESCONOCE</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="1488b47f" class="cell" title="Validación de nombres genéricos" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>valores_genericos <span class="op">=</span> [<span class="st">"DESCONOCIDO"</span>, <span class="st">"SIN NOMBRE"</span>, <span class="st">"N/A"</span>, <span class="st">"NO IDENTIFICADO"</span>, <span class="st">"NN"</span>]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>nombres_genericos <span class="op">=</span> df[df[<span class="st">"nombrecompleto"</span>].isin(valores_genericos)]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nombres genéricos o de relleno: </span><span class="sc">{</span><span class="bu">len</span>(nombres_genericos)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(nombres_genericos) <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    display(nombres_genericos[[<span class="st">"nombrecompleto"</span>, <span class="st">"fecha_desap"</span>, <span class="st">"entidad_desap"</span>]])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombres genéricos o de relleno: 0</code></pre>
</div>
</div>
</div>
<div class="card">
<h2 class="anchored" data-anchor-id="validaciones">
Resultados
</h2>
<div id="a51a3915" class="cell" title="Resumen de validaciones" data-execution_count="23">
<div class="cell-output cell-output-display" data-execution_count="23">
<style type="text/css">
#T_3db7e th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  font-size: 14px;
  text-align: left;
  padding: 10px;
}
#T_3db7e td {
  vertical-align: top;
  padding: 8px 10px;
  border-bottom: 1px solid #dcb685;
}
#T_3db7e_row0_col0, #T_3db7e_row0_col1, #T_3db7e_row0_col2, #T_3db7e_row1_col0, #T_3db7e_row1_col1, #T_3db7e_row1_col2, #T_3db7e_row2_col0, #T_3db7e_row2_col1, #T_3db7e_row2_col2 {
  font-size: 12px;
  text-align: left;
}
</style>

<table id="T_3db7e" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_3db7e_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Validación</th>
<th id="T_3db7e_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Registros afectados</th>
<th id="T_3db7e_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Acción tomada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_3db7e_row0_col0" class="data row0 col0">Fechas fuera de rango (&lt; 1950 o &gt; hoy)</td>
<td id="T_3db7e_row0_col1" class="data row0 col1">0</td>
<td id="T_3db7e_row0_col2" class="data row0 col2">Documentado, sin eliminación automática</td>
</tr>
<tr class="even">
<td id="T_3db7e_row1_col0" class="data row1 col0">Nombres con dígitos</td>
<td id="T_3db7e_row1_col1" class="data row1 col1">5</td>
<td id="T_3db7e_row1_col2" class="data row1 col2">Documentado, revisión individual</td>
</tr>
<tr class="odd">
<td id="T_3db7e_row2_col0" class="data row2 col0">Nombres genéricos o de relleno</td>
<td id="T_3db7e_row2_col1" class="data row2 col1">0</td>
<td id="T_3db7e_row2_col2" class="data row2 col2">Conservados, representan personas no identificadas</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">Resultados</h2>
<div class="{.layout-nrow=2}">
<div class="card">
<h2 class="anchored">
Implementación Final
</h2>
<p>A continuación se presentan todas las acciones realizadas para limpiar el dataset. En este código se considera el datset inicial “tot_reg_desap.csv” que hemos estado analizando hasta ahora. Como resultado del siguiente código se obteiene “dataset_limpio.csv”, el cual aplica todas las especificaciones que se han mencionado en la documentación.</p>
<div id="503b91fa" class="cell" title="Procesamiento del dataset" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> KNNImputer</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> OrdinalEncoder</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"tot_reg_desap.csv"</span>) <span class="co"># dataset inicial</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificación de tipo de dato booleano</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>columnas_booleanas <span class="op">=</span> [<span class="st">'rnpdno_json'</span>, <span class="st">'pre_rnped'</span>, <span class="st">'rnped'</span>, <span class="st">'rnpdno_csv'</span>, <span class="st">'bg_1'</span>, <span class="st">'bg_2'</span>]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> columnas_booleanas:</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].astype(<span class="bu">bool</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificación de texto normalizado</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>columnas_texto <span class="op">=</span> [<span class="st">'nombrecompleto'</span>, <span class="st">'fub'</span>, <span class="st">'DC_id'</span>]</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> columnas_texto:</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].astype(<span class="st">'string'</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformacion de fechas considerando múltiples fechas registradas</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].<span class="bu">str</span>.split(<span class="st">','</span>).<span class="bu">str</span>[<span class="dv">0</span>].<span class="bu">str</span>.strip()</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].replace({</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NA'</span>: np.nan, <span class="st">'nan'</span>: np.nan, <span class="st">'&lt;NA&gt;'</span>: np.nan, <span class="st">'None'</span>: np.nan, <span class="st">''</span>: np.nan</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'fecha_desap'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'mixed'</span>, dayfirst<span class="op">=</span><span class="va">True</span>, errors<span class="op">=</span><span class="st">'coerce'</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalización de categorías</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombres: mayúsculas y sin espacios extra</span></span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'nombrecompleto'</span>] <span class="op">=</span> df[<span class="st">'nombrecompleto'</span>].<span class="bu">str</span>.upper().<span class="bu">str</span>.strip()</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'nombrecompleto'</span>] <span class="op">=</span> df[<span class="st">'nombrecompleto'</span>].<span class="bu">str</span>.replace(<span class="vs">r'</span><span class="dv">\s</span><span class="op">+</span><span class="vs">'</span>, <span class="st">' '</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Entidad: mayúsculas, sin acentos</span></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> df[<span class="st">'entidad_desap'</span>].<span class="bu">str</span>.upper().<span class="bu">str</span>.strip()</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> (</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'entidad_desap'</span>]</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.normalize(<span class="st">'NFKD'</span>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.encode(<span class="st">'ascii'</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.decode(<span class="st">'utf-8'</span>)</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Estatus: primera letra mayúscula, resto minúscula, sin espacios</span></span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].<span class="bu">str</span>.capitalize().<span class="bu">str</span>.strip()</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir a category después de normalizar</span></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'entidad_desap'</span>] <span class="op">=</span> df[<span class="st">'entidad_desap'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Proceso de datos faltantes</span></span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a><span class="co"># estatus_busqueda: KNN</span></span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">'entidad_desap'</span>, <span class="st">'estatus_busqueda'</span>]</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a>df_knn <span class="op">=</span> df[cols].copy()</span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a>encoder <span class="op">=</span> OrdinalEncoder(handle_unknown<span class="op">=</span><span class="st">'use_encoded_value'</span>, unknown_value<span class="op">=</span>np.nan)</span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> encoder.fit_transform(df_knn)</span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a>imputer <span class="op">=</span> KNNImputer(n_neighbors<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a>df_imputed <span class="op">=</span> imputer.fit_transform(df_encoded)</span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a>df_imputed <span class="op">=</span> np.<span class="bu">round</span>(df_imputed)</span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a>df_decoded <span class="op">=</span> encoder.inverse_transform(df_imputed)</span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df_decoded[:, <span class="dv">1</span>]</span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'estatus_busqueda'</span>] <span class="op">=</span> df[<span class="st">'estatus_busqueda'</span>].astype(<span class="st">'category'</span>)</span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a><span class="co"># fecha_desap: imputación por moda de la entidad</span></span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a><span class="co"># La fecha imputada representa la moda del estado, no la fecha real</span></span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a>moda_por_entidad <span class="op">=</span> df.groupby(<span class="st">'entidad_desap'</span>)[<span class="st">'fecha_desap'</span>].transform(</span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: x.mode()[<span class="dv">0</span>] <span class="cf">if</span> <span class="kw">not</span> x.mode().empty <span class="cf">else</span> pd.NaT</span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fecha_desap'</span>] <span class="op">=</span> df[<span class="st">'fecha_desap'</span>].fillna(moda_por_entidad)</span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a><span class="co"># Columna index innecesaria</span></span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'Unnamed: 0'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Duplicados</span></span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a>df.drop_duplicates(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar y exportar el archivo</span></span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a>df.sort_values(by<span class="op">=</span><span class="st">'fecha_desap'</span>, ascending<span class="op">=</span><span class="va">False</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">'dataset_limpio.csv'</span>, index<span class="op">=</span><span class="va">False</span>, encoding<span class="op">=</span><span class="st">'utf-8'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div class="card">
<p>Para acceder al dataset después de aplicar los procedimientos anteriores: <a href="https://drive.google.com/file/d/16GlQ8A-6V7JGuKV2BkTT96iQX4OFHMxr/view?usp=sharing">dataset_limpio.csv</a></p>
</div>
</div>
</section>
</section>
<section id="medidas-visualización-e-interpretación" class="level1">
<h1>Medidas, Visualización e Interpretación</h1>
<section id="introducción-1" class="level2">
<h2 class="anchored" data-anchor-id="introducción-1">Introducción</h2>
<div class="card">
<p>Después de realizar la limpieza y transformación de los datos, podemos proceder al cálculo de las Medidas de Descriptivas que nos ayuden a entender que información contiene los datos para así poder dar una interpretación sustentada en datos verídicos y cumplir con los objetivos antes planteados.</p>
<p>Es importante mencionar que para realizar medidas con mayor enfoque a nuestras preguntas de análisis, se creo una variable llamada anio_desap, la cual fue obtenida a partir de la variable fecha_desap y contiene únicamente el año de desaparición. Para nuestros fines resulta conveniente esta creación de variable.</p>
</div>
</section>
<section id="row" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="row">Row</h2>
<section id="localización-tabla" class="level3">
<h3 class="anchored" data-anchor-id="localización-tabla">📍 Localización — Tabla</h3>
<div id="2846a4a9" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_00ba8 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  padding: 10px;
}
#T_00ba8 td {
  padding: 8px 12px;
  border-bottom: 1px solid #dcb685;
}
#T_00ba8 tr:hover td {
  background-color: #f0e8d8;
}
#T_00ba8_row0_col0, #T_00ba8_row0_col1, #T_00ba8_row0_col2, #T_00ba8_row1_col0, #T_00ba8_row1_col1, #T_00ba8_row1_col2, #T_00ba8_row2_col0, #T_00ba8_row2_col1, #T_00ba8_row2_col2, #T_00ba8_row3_col0, #T_00ba8_row3_col1, #T_00ba8_row3_col2, #T_00ba8_row4_col0, #T_00ba8_row4_col1, #T_00ba8_row4_col2, #T_00ba8_row5_col0, #T_00ba8_row5_col1, #T_00ba8_row5_col2, #T_00ba8_row6_col0, #T_00ba8_row6_col1, #T_00ba8_row6_col2, #T_00ba8_row7_col0, #T_00ba8_row7_col1, #T_00ba8_row7_col2 {
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_00ba8" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_00ba8_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Medida</th>
<th id="T_00ba8_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Valor</th>
<th id="T_00ba8_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Variable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_00ba8_row0_col0" class="data row0 col0">Media (año desaparición)</td>
<td id="T_00ba8_row0_col1" class="data row0 col1">2013.9</td>
<td id="T_00ba8_row0_col2" class="data row0 col2">anio_desap</td>
</tr>
<tr class="even">
<td id="T_00ba8_row1_col0" class="data row1 col0">Mediana (año desaparición)</td>
<td id="T_00ba8_row1_col1" class="data row1 col1">2015</td>
<td id="T_00ba8_row1_col2" class="data row1 col2">anio_desap</td>
</tr>
<tr class="odd">
<td id="T_00ba8_row2_col0" class="data row2 col0">Moda (año desaparición)</td>
<td id="T_00ba8_row2_col1" class="data row2 col1">2007</td>
<td id="T_00ba8_row2_col2" class="data row2 col2">anio_desap</td>
</tr>
<tr class="even">
<td id="T_00ba8_row3_col0" class="data row3 col0">Percentil 25 (Q1)</td>
<td id="T_00ba8_row3_col1" class="data row3 col1">2010</td>
<td id="T_00ba8_row3_col2" class="data row3 col2">anio_desap</td>
</tr>
<tr class="odd">
<td id="T_00ba8_row4_col0" class="data row4 col0">Percentil 75 (Q3)</td>
<td id="T_00ba8_row4_col1" class="data row4 col1">2019</td>
<td id="T_00ba8_row4_col2" class="data row4 col2">anio_desap</td>
</tr>
<tr class="even">
<td id="T_00ba8_row5_col0" class="data row5 col0">Percentil 90</td>
<td id="T_00ba8_row5_col1" class="data row5 col1">2021</td>
<td id="T_00ba8_row5_col2" class="data row5 col2">anio_desap</td>
</tr>
<tr class="odd">
<td id="T_00ba8_row6_col0" class="data row6 col0">Moda (entidad federativa)</td>
<td id="T_00ba8_row6_col1" class="data row6 col1">TAMAULIPAS</td>
<td id="T_00ba8_row6_col2" class="data row6 col2">entidad_desap</td>
</tr>
<tr class="even">
<td id="T_00ba8_row7_col0" class="data row7 col0">Moda (estatus de búsqueda)</td>
<td id="T_00ba8_row7_col1" class="data row7 col1">Se busca reportante</td>
<td id="T_00ba8_row7_col2" class="data row7 col2">estatus_busqueda</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="localización-gráfica" class="level3">
<h3 class="anchored" data-anchor-id="localización-gráfica">📍 Localización — Gráfica</h3>
<div id="e0c9845a" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea02_files/figure-html/cell-28-output-1.png" width="1235" height="379" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="localización-interpretación" class="level3">
<h3 class="anchored" data-anchor-id="localización-interpretación">📍 Localización — Interpretación</h3>
<p>El análisis de las medidas de tendencia central y posición revela una dinámica de crecimiento acelerado y una fuerte concentración institucional en el registro:</p>
<ul>
<li><p><strong>Análisis de Asimetría y Tendencia Temporal:</strong> La distribución presenta una <strong>asimetría negativa</strong> (hacia la izquierda), ya que la media (<strong>2013.9</strong>) se ubica por debajo de la mediana (<strong>2015</strong>). Esto indica que, aunque existen registros históricos aislados desde 1964 que “jalan” el promedio hacia atrás, la gran masa de datos se desplaza violentamente hacia la actualidad. La moda (<strong>2007</strong>) marca el punto máximo de registros, coincidiendo con el periodo de consolidación operativa del RNPDNO tras la Ley General de 2017.</p></li>
<li><p><strong>Concentración en el Rango Intercuartílico (IQR):</strong> Es notable que el <strong>50% central de los casos</strong> (entre el primer y tercer cuartil) se concentra en un periodo de apenas 6 años, entre <strong>2010</strong> y <strong>2019</strong>. Esto demuestra una intensificación drástica en la generación de folios en la última década o una mayor eficacia en la sistematización de datos recientes.</p></li>
<li><p><strong>Percentil 90 y Casos Críticos:</strong> El percentil 90 (<strong>2021</strong>) indica que nueve de cada diez registros corresponden a desapariciones ocurridas antes de ese año; sin embargo, esto también implica que el <strong>10% de todo el dataset</strong> (miles de casos) se ha registrado apenas entre 2022 y 2023.</p></li>
<li><p><strong>Predominancia Geográfica y de Estatus:</strong> La entidad federativa más frecuente es <strong>TAMAULIPAS</strong>, lo que refleja el foco crítico de este fenómeno en la frontera norte. Por otro lado, la moda en el estatus de búsqueda (<strong>Se busca reportante</strong>) revela que una gran parte del sistema depende administrativamente de la obtención de nuevos indicios o de la participación de los reportantes para procesar los expedientes.</p></li>
</ul>
</section>
</section>
<section id="row-1" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="row-1">Row</h2>
<section id="variabilidad-tabla" class="level3">
<h3 class="anchored" data-anchor-id="variabilidad-tabla">📊 Variabilidad — Tabla</h3>
<div id="7b153c8b" class="cell" data-execution_count="28">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_b1c03 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  padding: 10px;
}
#T_b1c03 td {
  padding: 8px 12px;
  border-bottom: 1px solid #dcb685;
}
#T_b1c03 tr:hover td {
  background-color: #f0e8d8;
}
#T_b1c03_row0_col0, #T_b1c03_row0_col1, #T_b1c03_row0_col2, #T_b1c03_row1_col0, #T_b1c03_row1_col1, #T_b1c03_row1_col2, #T_b1c03_row2_col0, #T_b1c03_row2_col1, #T_b1c03_row2_col2, #T_b1c03_row3_col0, #T_b1c03_row3_col1, #T_b1c03_row3_col2, #T_b1c03_row4_col0, #T_b1c03_row4_col1, #T_b1c03_row4_col2 {
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_b1c03" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_b1c03_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Medida</th>
<th id="T_b1c03_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Valor</th>
<th id="T_b1c03_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Unidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_b1c03_row0_col0" class="data row0 col0">Varianza</td>
<td id="T_b1c03_row0_col1" class="data row0 col1">44.08</td>
<td id="T_b1c03_row0_col2" class="data row0 col2">años²</td>
</tr>
<tr class="even">
<td id="T_b1c03_row1_col0" class="data row1 col0">Desviación estándar</td>
<td id="T_b1c03_row1_col1" class="data row1 col1">6.64</td>
<td id="T_b1c03_row1_col2" class="data row1 col2">años</td>
</tr>
<tr class="odd">
<td id="T_b1c03_row2_col0" class="data row2 col0">Rango total</td>
<td id="T_b1c03_row2_col1" class="data row2 col1">59</td>
<td id="T_b1c03_row2_col2" class="data row2 col2">años (1964–2023)</td>
</tr>
<tr class="even">
<td id="T_b1c03_row3_col0" class="data row3 col0">Rango intercuartílico (IQR)</td>
<td id="T_b1c03_row3_col1" class="data row3 col1">9</td>
<td id="T_b1c03_row3_col2" class="data row3 col2">años</td>
</tr>
<tr class="odd">
<td id="T_b1c03_row4_col0" class="data row4 col0">Coeficiente de variación</td>
<td id="T_b1c03_row4_col1" class="data row4 col1">0.3 %</td>
<td id="T_b1c03_row4_col2" class="data row4 col2">relativo</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="variabilidad-gráfica" class="level3">
<h3 class="anchored" data-anchor-id="variabilidad-gráfica">📊 Variabilidad — Gráfica</h3>
<div id="e24398ac" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea02_files/figure-html/cell-30-output-1.png" width="1238" height="382" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="variabilidad-interpretación" class="level3">
<h3 class="anchored" data-anchor-id="variabilidad-interpretación">📊 Variabilidad — Interpretación</h3>
<p>El análisis de la dispersión temporal permite identificar cómo se distribuye la crisis de desapariciones a través de las décadas, revelando una estructura de datos altamente concentrada pero con una memoria histórica extensa:</p>
<ul>
<li><p><strong>Dispersión vs.&nbsp;Memoria Histórica:</strong> La desviación estándar de <strong>6.6</strong> años indica una dispersión considerable respecto a la media. Sin embargo, el <strong>rango total de 59 años</strong> (1964–2023) es lo que verdaderamente dimensiona la cronicidad del problema, integrando registros que datan desde la época de la llamada “Guerra Sucia” hasta la actualidad.</p></li>
<li><p><strong>El Fenómeno de la “Caja Estrecha” (IQR):</strong> El dato más revelador es el <strong>Rango Intercuartílico (IQR) de solo 9 años</strong>. Esto significa que, a pesar de que el dataset abarca casi seis décadas, el <strong>50% de todos los casos registrados</strong> se asfixia en una ventana temporal sumamente breve (2013–2019). Esta concentración masiva sugiere una “aceleración” del fenómeno o un sesgo de captura institucional en años recientes.</p></li>
<li><p><strong>Análisis de Valores Atípicos (Outliers):</strong> En el Boxplot general, se observa una densa estela de valores atípicos que se extiende hacia el pasado (antes de 2005). Estos puntos representan la resistencia de los registros históricos que, aunque numéricamente son menos que los actuales, mantienen viva la trazabilidad de desapariciones de décadas anteriores en el sistema nacional.</p></li>
<li><p><strong>Variabilidad por Entidad (Top 6):</strong> Al comparar los estados con mayor incidencia, se nota que <strong>Tamaulipas y el Estado de México</strong> presentan “bigotes” más largos y una mayor cantidad de valores atípicos hacia años antiguos, lo que refleja una problemática de mayor data. Por el contrario, entidades como <strong>Jalisco o Michoacán</strong> muestran cajas (IQR) posicionadas de forma más compacta en el extremo superior del gráfico, sugiriendo que el volumen masivo de sus registros es un fenómeno predominantemente más reciente o de reporte tardío.</p></li>
<li><p><strong>Coeficiente de Variación (CV):</strong> El valor de <strong>0.3%</strong> refleja una dispersión relativa baja respecto a la magnitud de los años, lo cual es típico en variables temporales de este tipo, pero confirma que la transición entre el RNPED y el RNPDNO no rompió la continuidad estadística de la tendencia central.</p></li>
</ul>
</section>
</section>
<section id="row-2" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="row-2">Row</h2>
<section id="heterogeneidad-tabla" class="level3">
<h3 class="anchored" data-anchor-id="heterogeneidad-tabla">🔀 Heterogeneidad — Tabla</h3>
<div id="149ad0a2" class="cell" data-execution_count="30">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_3518e th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  padding: 10px;
}
#T_3518e td {
  padding: 8px 12px;
  border-bottom: 1px solid #dcb685;
}
#T_3518e tr:hover td {
  background-color: #f0e8d8;
}
#T_3518e_row0_col0, #T_3518e_row0_col1, #T_3518e_row0_col2, #T_3518e_row0_col3, #T_3518e_row0_col4, #T_3518e_row1_col0, #T_3518e_row1_col1, #T_3518e_row1_col2, #T_3518e_row1_col3, #T_3518e_row1_col4 {
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_3518e" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_3518e_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th id="T_3518e_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Categorías</th>
<th id="T_3518e_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Entropía H (bits)</th>
<th id="T_3518e_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">H normalizada [0–1]</th>
<th id="T_3518e_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Índice Simpson D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_3518e_row0_col0" class="data row0 col0">entidad_desap</td>
<td id="T_3518e_row0_col1" class="data row0 col1">33</td>
<td id="T_3518e_row0_col2" class="data row0 col2">4.358</td>
<td id="T_3518e_row0_col3" class="data row0 col3">0.864</td>
<td id="T_3518e_row0_col4" class="data row0 col4">0.9365</td>
</tr>
<tr class="even">
<td id="T_3518e_row1_col0" class="data row1 col0">estatus_busqueda</td>
<td id="T_3518e_row1_col1" class="data row1 col1">9</td>
<td id="T_3518e_row1_col2" class="data row1 col2">2.029</td>
<td id="T_3518e_row1_col3" class="data row1 col3">0.640</td>
<td id="T_3518e_row1_col4" class="data row1 col4">0.7171</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="heterogeneidad-gráfica" class="level3">
<h3 class="anchored" data-anchor-id="heterogeneidad-gráfica">🔀 Heterogeneidad — Gráfica</h3>
<div id="3c6b71af" class="cell" data-execution_count="31">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea02_files/figure-html/cell-32-output-1.png" width="1239" height="382" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="heterogeneidad-interpretación" class="level3">
<h3 class="anchored" data-anchor-id="heterogeneidad-interpretación">🔀 Heterogeneidad — Interpretación</h3>
<p>El análisis de diversidad y entropía permite cuantificar qué tan equilibrada está la información o si existen sesgos de concentración que dominen el dataset:</p>
<ul>
<li><strong>Diversidad Geográfica (Entidad Federativa):</strong>
<ul>
<li><strong>Índice de Simpson (D = 0.9365):</strong> Este valor es notablemente alto (0.9366). Significa que existe una probabilidad del <strong>93.6%</strong> de que, si seleccionamos dos registros al azar, estos pertenezcan a estados diferentes. Esto confirma que la desaparición es un fenómeno de alcance nacional y no está confinado a una sola región.</li>
<li><strong>Entropía Normalizada (H_norm = 0.864):</strong> Aunque la diversidad es alta, el hecho de que no sea 1.0 indica que la “incertidumbre” no es máxima. Como se observa en la gráfica de barras, estados como <strong>Tamaulipas y el Estado de México</strong> actúan como “atractores” masivos de registros, impidiendo que la distribución sea perfectamente uniforme a través de las 33 entidades.</li>
</ul></li>
<li><strong>Concentración en el Estatus de Búsqueda:</strong>
<ul>
<li><strong>Entropía Normalizada (H_norm = 0.640):</strong> Este valor es significativamente menor al geográfico (0.604), alejándose un <strong>40% de la uniformidad teórica</strong>. Con solo 9 categorías, el sistema tiende a “encasillar” la mayoría de los casos en etiquetas específicas.</li>
<li><strong>Dominancia Administrativa:</strong> La categoría <strong>“Se busca reportante”</strong> domina visualmente la gráfica, lo cual explica el Índice de Simpson más bajo (<strong>0.7171</strong>). Esta alta concentración sugiere un proceso de <strong>reclasificación masiva</strong>; es decir, la autoridad utiliza categorías administrativas genéricas para gestionar grandes volúmenes de datos, lo que introduce un sesgo oficialista que podría simplificar la complejidad real de los procesos de localización.</li>
</ul></li>
<li><strong>Incertidumbre Informativa:</strong> La combinación de una alta diversidad geográfica con una baja diversidad de estatus revela una paradoja técnica: mientras que el origen de los casos es heterogéneo (ocurre en todo el país), el resultado administrativo es homogéneo (se clasifican bajo los mismos pocos términos), lo que apunta a una <strong>estandarización burocrática</strong> del fenómeno.</li>
</ul>
</section>
</section>
<section id="row-3" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="row-3">Row</h2>
<section id="concentración-tabla" class="level3">
<h3 class="anchored" data-anchor-id="concentración-tabla">📐 Concentración — Tabla</h3>
<div id="a00e7365" class="cell" data-execution_count="32">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_3a9c6 th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  padding: 10px;
}
#T_3a9c6 td {
  padding: 8px 12px;
  border-bottom: 1px solid #dcb685;
}
#T_3a9c6 tr:hover td {
  background-color: #f0e8d8;
}
#T_3a9c6_row0_col0, #T_3a9c6_row0_col1, #T_3a9c6_row0_col2, #T_3a9c6_row1_col0, #T_3a9c6_row1_col1, #T_3a9c6_row1_col2 {
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_3a9c6" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_3a9c6_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable</th>
<th id="T_3a9c6_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Índice de Gini</th>
<th id="T_3a9c6_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_3a9c6_row0_col0" class="data row0 col0">entidad_desap</td>
<td id="T_3a9c6_row0_col1" class="data row0 col1">0.5253</td>
<td id="T_3a9c6_row0_col2" class="data row0 col2">Top 20% de entidades (7 estados) concentran 54.4% de casos</td>
</tr>
<tr class="even">
<td id="T_3a9c6_row1_col0" class="data row1 col0">anio_desap</td>
<td id="T_3a9c6_row1_col1" class="data row1 col1">0.7754</td>
<td id="T_3a9c6_row1_col2" class="data row1 col2">Concentración temporal de registros por año</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="concentración-gráfica" class="level3">
<h3 class="anchored" data-anchor-id="concentración-gráfica">📐 Concentración — Gráfica</h3>
<div id="e70216ad" class="cell" data-execution_count="33">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea02_files/figure-html/cell-34-output-1.png" width="1238" height="473" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="concentración-interpretación" class="level3">
<h3 class="anchored" data-anchor-id="concentración-interpretación">📐 Concentración — Interpretación</h3>
<p>El análisis de concentración mediante el Índice de Gini y las Curvas de Lorenz permite identificar desequilibrios críticos en cómo se registran los casos en el territorio y a través del tiempo:</p>
<ul>
<li><strong>Concentración Geográfica (Desigualdad Territorial):</strong>
<ul>
<li><strong>Índice de Gini (0.5253):</strong> Un valor de <strong>0.5253</strong> confirma una <strong>concentración moderada-alta</strong>. En el gráfico, la curva marrón se aleja significativamente de la diagonal de igualdad perfecta, lo que indica que el fenómeno no está distribuido de manera equitativa ni uniforme.</li>
<li><strong>Regla del 20/50:</strong> El hallazgo más impactante es que el <strong>20% de las entidades más afectadas</strong> (apenas 7 estados como <strong>Tamaulipas, Estado de México y Veracruz</strong>) concentran el <strong>54.4% del total de casos</strong>. Esto sugiere que más de la mitad de la crisis nacional se localiza en focos rojos específicos vinculados históricamente a rutas de violencia organizada y disputas territoriales.</li>
</ul></li>
<li><strong>Concentración Temporal (El “Salto” Institucional):</strong>
<ul>
<li><strong>Índice de Gini (0.7754):</strong> Este valor de <strong>0.7569</strong> es extremadamente alto, acercándose a la concentración total. La Curva de Lorenz turquesa permanece casi plana durante el 70% de las categorías anuales, para luego dispararse de forma casi vertical al final.</li>
<li><strong>Efecto de Visibilidad Administrativa:</strong> Esta forma de “L” invertida refleja que la gran mayoría de los registros del dataset pertenecen a una ventana de tiempo muy pequeña. Más que un aumento repentino en el número real de delitos, este comportamiento evidencia el impacto de la <strong>Ley General de 2017</strong>, que obligó a una centralización masiva de datos antes dispersos o inexistentes en el sistema oficial.</li>
</ul></li>
<li><strong>Comparativa Técnica:</strong> Mientras que la concentración geográfica (Gini 0.52) refleja un problema de seguridad regional, la concentración temporal (Gini 0.75) es un reflejo de la <strong>evolución de los sistemas de información del Estado</strong>. La “desigualdad” en los años se debe a que hoy el Estado tiene herramientas de registro que en 1970 no existían, invisibilizando estadísticamente el pasado frente a un presente densamente documentado.</li>
</ul>
</section>
</section>
</section>
<section id="correlación" class="level1">
<h1>Correlación</h1>
<section id="row-4" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="row-4">Row</h2>
<section id="tabla-de-correlaciones" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-correlaciones">📊 Tabla de correlaciones</h3>
<div id="5c097939" class="cell" data-execution_count="35">
<div class="cell-output cell-output-display">
<style type="text/css">
#T_6106c th {
  background-color: #4d2c18;
  color: white;
  font-weight: bold;
  padding: 10px;
}
#T_6106c td {
  padding: 8px 12px;
  border-bottom: 1px solid #dcb685;
}
#T_6106c tr:hover td {
  background-color: #f0e8d8;
}
#T_6106c_row0_col0, #T_6106c_row0_col1, #T_6106c_row0_col3, #T_6106c_row1_col0, #T_6106c_row1_col1, #T_6106c_row1_col3, #T_6106c_row2_col0, #T_6106c_row2_col1, #T_6106c_row2_col3, #T_6106c_row3_col0, #T_6106c_row3_col1, #T_6106c_row3_col3, #T_6106c_row4_col0, #T_6106c_row4_col1, #T_6106c_row4_col3, #T_6106c_row5_col0, #T_6106c_row5_col1, #T_6106c_row5_col3, #T_6106c_row6_col0, #T_6106c_row6_col1, #T_6106c_row6_col3, #T_6106c_row7_col0, #T_6106c_row7_col1, #T_6106c_row7_col3, #T_6106c_row8_col0, #T_6106c_row8_col1, #T_6106c_row8_col3, #T_6106c_row9_col0, #T_6106c_row9_col1, #T_6106c_row9_col3 {
  text-align: left;
  font-size: 13px;
}
#T_6106c_row0_col2 {
  background-color: #04703b;
  color: #f1f1f1;
  text-align: left;
  font-size: 13px;
}
#T_6106c_row1_col2 {
  background-color: #249d53;
  color: #f1f1f1;
  text-align: left;
  font-size: 13px;
}
#T_6106c_row2_col2 {
  background-color: #30a356;
  color: #f1f1f1;
  text-align: left;
  font-size: 13px;
}
#T_6106c_row3_col2 {
  background-color: #33a456;
  color: #f1f1f1;
  text-align: left;
  font-size: 13px;
}
#T_6106c_row4_col2 {
  background-color: #73c264;
  color: #000000;
  text-align: left;
  font-size: 13px;
}
#T_6106c_row5_col2, #T_6106c_row6_col2, #T_6106c_row7_col2, #T_6106c_row8_col2, #T_6106c_row9_col2 {
  background-color: #000000;
  color: #f1f1f1;
  text-align: left;
  font-size: 13px;
}
</style>

<table id="T_6106c" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_6106c_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Variable 1</th>
<th id="T_6106c_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Variable 2</th>
<th id="T_6106c_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Correlación</th>
<th id="T_6106c_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_6106c_row0_col0" class="data row0 col0">bg_2</td>
<td id="T_6106c_row0_col1" class="data row0 col1">bg_1</td>
<td id="T_6106c_row0_col2" class="data row0 col2">0.9668</td>
<td id="T_6106c_row0_col3" class="data row0 col3">Más fuertes</td>
</tr>
<tr class="even">
<td id="T_6106c_row1_col0" class="data row1 col0">bg_1</td>
<td id="T_6106c_row1_col1" class="data row1 col1">rnpdno_csv</td>
<td id="T_6106c_row1_col2" class="data row1 col2">0.7666</td>
<td id="T_6106c_row1_col3" class="data row1 col3">Más fuertes</td>
</tr>
<tr class="odd">
<td id="T_6106c_row2_col0" class="data row2 col0">bg_2</td>
<td id="T_6106c_row2_col1" class="data row2 col1">rnpdno_csv</td>
<td id="T_6106c_row2_col2" class="data row2 col2">0.7414</td>
<td id="T_6106c_row2_col3" class="data row2 col3">Más fuertes</td>
</tr>
<tr class="even">
<td id="T_6106c_row3_col0" class="data row3 col0">rnpdno_csv</td>
<td id="T_6106c_row3_col1" class="data row3 col1">rnpdno_json</td>
<td id="T_6106c_row3_col2" class="data row3 col2">0.7291</td>
<td id="T_6106c_row3_col3" class="data row3 col3">Más fuertes</td>
</tr>
<tr class="odd">
<td id="T_6106c_row4_col0" class="data row4 col0">bg_1</td>
<td id="T_6106c_row4_col1" class="data row4 col1">rnpdno_json</td>
<td id="T_6106c_row4_col2" class="data row4 col2">0.5590</td>
<td id="T_6106c_row4_col3" class="data row4 col3">Más fuertes</td>
</tr>
<tr class="even">
<td id="T_6106c_row5_col0" class="data row5 col0">bg_1</td>
<td id="T_6106c_row5_col1" class="data row5 col1">bg_2</td>
<td id="T_6106c_row5_col2" class="data row5 col2">nan</td>
<td id="T_6106c_row5_col3" class="data row5 col3">Más débiles</td>
</tr>
<tr class="odd">
<td id="T_6106c_row6_col0" class="data row6 col0">bg_1</td>
<td id="T_6106c_row6_col1" class="data row6 col1">anio_desap</td>
<td id="T_6106c_row6_col2" class="data row6 col2">nan</td>
<td id="T_6106c_row6_col3" class="data row6 col3">Más débiles</td>
</tr>
<tr class="even">
<td id="T_6106c_row7_col0" class="data row7 col0">bg_2</td>
<td id="T_6106c_row7_col1" class="data row7 col1">bg_2</td>
<td id="T_6106c_row7_col2" class="data row7 col2">nan</td>
<td id="T_6106c_row7_col3" class="data row7 col3">Más débiles</td>
</tr>
<tr class="odd">
<td id="T_6106c_row8_col0" class="data row8 col0">bg_2</td>
<td id="T_6106c_row8_col1" class="data row8 col1">anio_desap</td>
<td id="T_6106c_row8_col2" class="data row8 col2">nan</td>
<td id="T_6106c_row8_col3" class="data row8 col3">Más débiles</td>
</tr>
<tr class="even">
<td id="T_6106c_row9_col0" class="data row9 col0">anio_desap</td>
<td id="T_6106c_row9_col1" class="data row9 col1">anio_desap</td>
<td id="T_6106c_row9_col2" class="data row9 col2">nan</td>
<td id="T_6106c_row9_col3" class="data row9 col3">Más débiles</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="heatmap-de-correlaciones" class="level3">
<h3 class="anchored" data-anchor-id="heatmap-de-correlaciones">🗺️ Heatmap de Correlaciones</h3>
<div id="03e40036" class="cell" data-execution_count="36">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tarea02_files/figure-html/cell-37-output-1.png" width="724" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretación" class="level3">
<h3 class="anchored" data-anchor-id="interpretación">📝 Interpretación</h3>
<p>Las <strong>correlaciones más fuertes</strong> encontradas son: <strong>bg_2 ↔︎ bg_1 (0.967); bg_1 ↔︎ rnpdno_csv (0.767); bg_2 ↔︎ rnpdno_csv (0.741)</strong>.</p>
<p>Estas asociaciones reflejan una alta coherencia interna en las etapas de la Búsqueda Generalizada, pero también revelan una <strong>brecha técnica</strong>: la correlación de <strong>0.73</strong> entre el JSON y el CSV del RNPDNO confirma que los ciudadanos acceden a información distinta dependiendo del formato que consulten.</p>
<p>Por otro lado, las <strong>correlaciones negativas</strong> con los registros históricos (<code>pre_rnped</code> y <code>rnped</code>) sugieren que una parte considerable de la memoria histórica del RNPED no logró transitar exitosamente hacia las nuevas plataformas digitales.</p>
<p>Finalmente, las <strong>correlaciones más débiles</strong> corresponden a: <strong>bg_2 ↔︎ bg_2 (nan); bg_2 ↔︎ anio_desap (nan); anio_desap ↔︎ anio_desap (nan)</strong>. La nula asociación con <code>anio_desap</code> es un hallazgo fundamental: demuestra que la visibilidad de una persona desaparecida en los registros oficiales es un proceso <strong>discrecional y administrativo</strong>, totalmente independiente de qué tan antiguo o reciente sea el caso.</p>
</section>
</section>
</section>
<section id="hallazgos" class="level1">
<h1>Hallazgos</h1>
<section id="row-5" class="level2">
<h2 class="anchored" data-anchor-id="row-5">Row</h2>
<div class="card">
<section id="hallazgo-1---concentración-geográfica-en-pocas-entidades" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-1---concentración-geográfica-en-pocas-entidades">Hallazgo 1 - Concentración geográfica en pocas entidades</h3>
<p>El análisis de la distribución de casos por entidad federativa muestra que las desapariciones en México no afectan de manera homogénea al territorio nacional. El índice de Gini, calculado sobre los registros de personas desaparecidas, arroja un valor de 0.5253 (en una escala de 0 a 1, donde 0 representa igualdad perfecta y 1 concentración absoluta). Este indicador confirma una concentración moderada‑alta, evidenciando que un número reducido de estados acumula una proporción desproporcionadamente alta de los casos. En términos concretos, el 20% de las entidades con mayor incidencia (es decir, 7 de las 32 entidades) concentra el 54.4% del total de registros. Entre ellas destacan Tamaulipas, Estado de México y Veracruz, que ocupan los primeros lugares en volumen de casos. Estas regiones han sido señaladas históricamente por la presencia de grupos del crimen organizado, rutas de tráfico de personas y disputas territoriales, factores que explican en parte la alta incidencia. Además, en estos estados se han documentado hallazgos de fosas clandestinas y patrones de desaparición recurrente, lo que refuerza la gravedad del fenómeno en esas zonas. La desigualdad geográfica se visualiza con claridad en la curva de Lorenz: la línea se aparta notablemente de la diagonal de igualdad perfecta, mostrando que una minoría de entidades absorbe la mayor parte de los registros. Esta asimetría no es un dato menor; tiene implicaciones directas para el diseño de políticas públicas. Los esfuerzos de búsqueda, los recursos forenses y las estrategias de prevención no pueden ser uniformes en todo el país. Deben focalizarse de manera diferenciada, priorizando aquellas entidades donde la crisis es estructural y donde se concentra la mayor parte de la carga de casos sin resolver.</p>
</section>
<section id="hallazgo-2---crecimiento-sostenido-de-registros-a-partir-del-2007" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-2---crecimiento-sostenido-de-registros-a-partir-del-2007">Hallazgo 2 - Crecimiento sostenido de registros a partir del 2007</h3>
<p>La distribución temporal del año de desaparición nos da como resultado una tendencia que nos dice que los registros van mostrando un crecimiento progresivo y sostenido desde el año 2007, la cual ha tenido una aceleración a partir del año 2018. Este patrón no solo es visible en el volumen anual de casos, sino también en las medidas de tendencia central y forma de la distribución. La media del año de desaparición se ubica por encima de la mediana, lo cual indica que los años más recientes jalan la media hacia adelante, generando una asimetría positiva, lo que significa que los registros se van a concentrar en los últimos años del periodo. La moda va a corresponder a los años más actuales dentro del conjunto de datos confirmando que el mayor volumen de casos se ubica hasta el extremo más reciente de la serie temporal. La moda va a corresponder a los años más actuales dentro del dataset, confirmando que el volumen más alto de registros se concentra en los últimos años del periodo. Podemos ver que este comportamiento tiene que ver que en el año 2017 entró en vigor la Ley General en Materia de Desaparición Forzada de Personas, que creó el RNPDNO que obliga a las autoridades a homologar y centralizar la información, lo que provocó que muchos casos que no estaban sistematizados comenzaron a registrar masivamente, dando como resultado que muchos casos que anteriormente se encontraban dispersos en registros estatales, en archivos ministeriales o simplemente no estaban sistematizados y se empezaron a incorporarse masivamente al nuevo sistema dando un tipo de “inflamiento” estadístico en los años posteriors del 2018 que responde a una mejora en la visibilidad y sistematización de la información que tal vez a un incremento proporcional en la incidencia real del delito. La distinción crucial que tenemos que tener en cuenta es que no debemos confundir un aumento en los registros con un aumento en las desapariciones, solo es un reflejo del cambio del régimen del registro.</p>
</section>
<section id="hallazgo-3---estatus-de-búsqueda-se-busca-reportante" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-3---estatus-de-búsqueda-se-busca-reportante">Hallazgo 3 - Estatus de búsqueda: “Se busca reportante”</h3>
<p>La moda en la variable correspondiente al estatus de búsqueda es “Se busca reportante”. Al ser la categoría más encontrada en los registros nos da un indicio de que gran parte de estos presentan un bloqueo de proceso, es decir, la persona que realizó la denuncia no ha dado seguimiento al caso o las autoridades no la han podido localizar. El índice de Simpson como medida de heterogeneidad para la variable correspondiente al estatus es de 0.7171, lo que significa que si se tomaran dos casos al azar del dataset, existe una probabilidad del 71.7% de que pertenezcan a categorías de estatus distintas, lo que indica diversidad real en los resultados. Sin embargo, cómo la presencia de esta variable es muy notable a través de la moda, nos sugiere que esta categoría absorbe una cantidad desproporcionada de los registros.</p>
<p>La entropía normalizada de estatus_busqueda es 0.64, notablemente más baja que la de entidad_desap (0.864). Esto significa que aunque hay 9 categorías posibles de estatus, la distribución entre ellas es considerablemente menos uniforme que la distribución geográfica, algunas categorías concentran muchos más casos que otras. En una distribución perfectamente uniforme con 9 categorías la entropía normalizada sería 1, por lo que el valor de 0.64 indica que aproximadamente el 40% de la capacidad de diversidad del sistema de estatus no se está utilizando, porque los casos tienden a acumularse en pocas categorías dominantes. Esto nos describe un sistema donde hay diversidad formal de categorías pero concentración real en el estatus menos resolutivo. Este hallazgo expone una falla estructural en el seguimiento institucional de los casos. “Se busca reportante” implica que la carga del proceso recae sobre la familia o persona que realizó la denuncia (si no hay contacto activo con el denunciante, el caso queda en suspenso). En un contexto donde muchas familias denunciantes enfrentan amenazas, desconfianza institucional o simplemente falta de recursos para dar seguimiento, este estatus puede convertirse en un mecanismo involuntario de archivo de casos sin resolución. El dataset no permite distinguir cuántos de estos casos están en suspenso por falta de respuesta de la familia versus por falta de gestión institucional, lo que constituye una limitación importante pero también una pregunta de investigación relevante para estudios posteriores.</p>
</section>
<section id="hallazgo-4---variabilidad-heterogénea-entre-las-entidades" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-4---variabilidad-heterogénea-entre-las-entidades">Hallazgo 4 - Variabilidad heterogénea entre las entidades</h3>
<p>El análisis de dispersión del año de desaparición muestra que la variabilidad no es homogénea entre las 32 entidades federativas. El rango intercuartílico (IQR) global de los años de desaparición se ubica en 9 años, lo que indica que el 50% central de los registros se concentra en ese intervalo de tiempo. Sin embargo, cuando se desagrega por entidad mediante el boxplot, se observan comportamientos radicalmente distintos: algunos estados presentan una dispersión amplia que abarca varias décadas, mientras que otros tienen una caja muy estrecha, lo que revela que sus registros se concentran en un periodo muy específico. Los estados con mayor IQR, como Tamaulipas, sugieren una problemática crónica y estructural: sus desapariciones no son un fenómeno reciente ni puntual, sino que se distribuyen a lo largo de muchos años, lo que puede reflejar violencia sostenida en el tiempo o una acumulación histórica de casos sin resolver que finalmente fueron sistematizados al crearse el RNPDNO. En contraste, entidades con IQR reducido y valores recientes podrían estar asociadas a crisis específicas y más recientes, posiblemente vinculadas a reconfiguración del crimen organizado o a estallidos de violencia localizados en periodos concretos. La presencia de valores atípicos (outliers) en varios estados, visibles en el boxplot como puntos fuera de los bigotes, corresponde a registros con fechas muy antiguas — algunos anteriores a 2000 — que probablemente provienen del RNPED histórico (pre_rnped == 1) y que fueron incorporados tardíamente al sistema unificado. Esta heterogeneidad en la dispersión refuerza la necesidad de no tratar el fenómeno de manera uniforme: una política de búsqueda diseñada para casos recientes no responde a las necesidades de entidades con casos que acumulan más de 15 o 20 años de antigüedad sin resolución.</p>
</section>
<section id="hallazgo-5---búsqueda-generalizada-relacionada-con-rnped-y-rnpdno" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-5---búsqueda-generalizada-relacionada-con-rnped-y-rnpdno">Hallazgo 5 - Búsqueda Generalizada relacionada con RNPED y RNPDNO</h3>
<p>Al centrarnos en las variables bg_1 y bg_2, observamos que tienen una alta correlación con rnpdno_csv y en menor medida con rnpdno_json. Ahora, si comparamos estos números con los correspondientes a pre_rnped y rnped podemos observar la gran diferencia entre cómo se relacionan. Al analizar la matriz de correlación, se observa una relación casi perfecta (0.97) entre las fases de Búsqueda Generalizada (bg_1 y bg_2), lo que indica que ambas etapas operaron sobre prácticamente la misma población de casos, esto significa que la segunda fase no representó una ampliación territorial o administrativa para incluir expedientes rezagados, sino que fue una revisión iterativa sobre el mismo grupo de personas que ya había sido seleccionado en la fase inicial. La fuerte asociación positiva de las fases de búsqueda con el registro público actual (rnpdno_csv, con 0.77 y 0.74) contrasta abruptamente con la correlación negativa que mantienen con el padrón histórico (rnped, con -0.25 y -0.23). Esta discrepancia matemática expone un sesgo sistemático, los recientes esfuerzos masivos de búsqueda priorizaron de manera casi exclusiva los expedientes de la nueva plataforma, dejando inactivos o marginados los casos más antiguos.</p>
</section>
<section id="hallazgo-6---registros-históricos-que-desaparecieron-del-sistema-oficial" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-6---registros-históricos-que-desaparecieron-del-sistema-oficial">Hallazgo 6 - Registros históricos que desaparecieron del sistema oficial</h3>
<p>Cuando se creó el RNPDNO en 2018, no todos los casos que existían en el registro anterior (RNPED) fueron trasladados a la nueva base de datos. Al cruzar las columnas pre_rnped, rnped y rnpdno_csv, podemos identificar exactamente cuántas personas que alguna vez estuvieron registradas como desaparecidas dejaron de aparecer en el sistema público actual, sin que exista una explicación oficial de por qué fueron retiradas. Esto no es un error menor: significa que hay personas cuya búsqueda quedó suspendida administrativamente. Sus familias siguen buscándolas, pero el Estado dejó de contarlas. Y al no estar en el RNPDNO, tampoco fueron consideradas en la Búsqueda Generalizada, que como vimos en el hallazgo anterior, operó casi exclusivamente sobre los registros de la nueva plataforma. Lo más preocupante es que esta exclusión no ocurrió de manera pareja en todo el país. Hay estados con tasas de omisión mucho más altas que otros, lo que indica que no fue un proceso técnico neutral, sino uno que afectó de forma desigual a ciertas regiones, especialmente aquellas con registros más antiguos, anteriores a 2018.</p>
</section>
<section id="hallazgo-7---la-desaparición-es-un-fenómeno-nacional-pero-con-epicentros-muy-marcados" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-7---la-desaparición-es-un-fenómeno-nacional-pero-con-epicentros-muy-marcados">Hallazgo 7 - La desaparición es un fenómeno nacional, pero con epicentros muy marcados</h3>
<p>La distribución por entidad federativa muestra una entropía de Shannon normalizada de H_norm = 0.864, lo que significa que las desapariciones no están concentradas en un solo estado: están presentes en las 32 entidades y en “Se desconoce”, lo que confirma que es un problema que afecta a todo el país sin excepción. Sin embargo, el índice de Simpson de D = 0.9366 y la propia gráfica de barras cuentan la otra cara: si bien hay diversidad geográfica, existen dos picos que se separan visiblemente del resto: Tamaulipas (~12,000) y el Estado de México (~11,000). Estos dos estados por sí solos concentran una proporción desproporcionada respecto al resto de entidades, que descienden abruptamente hacia Veracruz (~6,000) y los demás. Esto significa que aunque el fenómeno es nacional en su alcance, no es uniforme en su intensidad. Hay epicentros donde la problemática es estructural y acumulada, mientras que la gran mayoría de los estados tienen números relativamente bajos. Una política pública que trate a todos los estados por igual estaría ignorando esta asimetría.</p>
</section>
<section id="hallazgo-8---la-mayoría-de-los-casos-con-progreso-real-son-una-minoría-dentro-del-sistema" class="level3">
<h3 class="anchored" data-anchor-id="hallazgo-8---la-mayoría-de-los-casos-con-progreso-real-son-una-minoría-dentro-del-sistema">Hallazgo 8 - La mayoría de los casos con progreso real son una minoría dentro del sistema</h3>
<p>Al analizar la distribución de estatus de búsqueda, las categorías que implican algún avance concreto “Con indicios / Ubicada” (12,580) y “Denuncia confirmada” (15,659) suman alrededor de 28,000 casos. Aunque no es un número menor, representa una fracción pequeña frente a las casi 42,000 personas cuyo estatus es “Se busca reportante” o “Se requieren datos de identidad”, que son categorías sin resolución activa. Al cruzar este dato con el heatmap de correlación, donde bg_1 y bg_2 tienen una correlación de 0.77 y 0.74 con rnpdno_csv, se puede inferir que los casos con mayor probabilidad de tener un estatus resolutivo son precisamente aquellos que entraron al registro actual y a la Búsqueda Generalizada. Los registros históricos del RNPED (rnped), con correlación negativa (-0.25, -0.23) con las fases de búsqueda, quedaron fuera de este proceso y probablemente concentran la mayor parte de los casos sin actualización de estatus. Finalmente, las categorías híbridas al fondo del gráfico como “Se requieren datos de identidad, Se busca reportante” (16 casos) o “Con indicios / Ubicada, Se requieren datos de identidad” (27 casos) — aunque son numéricamente marginales, evidencian una inconsistencia en el sistema de clasificación: hay casos que no encajan en ninguna categoría única, lo que apunta a limitaciones en los criterios de registro del RNPDNO.</p>
</section>
</div>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>La descripción de la aplicación del framework CRISP-DM ofrece un panorama de análisis que ayuda a establecer objetivos y avanzar de manera efectiva en el procesamiento de los datos. Aplicado a un conjunto de datos que contiene información de los registros de personas desaparecidas en México junto con datos de su presencia en los registros RNPED o RNPDNO permitió tener un flujo de trabajo organizado con metas claras.</p>
<p>Respecto a las etapas de esta metodología, la comprensión del negocio consistió en abarcar todo el contexto de esta crisis en México, no sólo se trata de mirar cifras, sino de reconocer que cada registro representa una vida y una familia. En las etapas de comprensión y preparación de Datos fue fundamental la observación de las variables con las que se contaban y cómo funcionaban para representar los registros, es una de las partes más delicadas porque se buscó evitar introducir sesgos en el manejo de datos faltantes. No se llevaron a cabo modelos de Minería de Datos, sin embargo, se sugirieron algunas aplicaciones que podrían realizarse en este trabajo. Por último, en la parte de evaluación y despliegue es donde vemos como queda plasmado todos los procedimientos anteriores y donde podemos finalmente responder a nuestras preguntas y objetivos planteados.</p>
<p>A partir de la exploración de los registros oficiales de personas desaparecidas en México, se extraen las siguientes conclusiones fundamentales que dimensionan la crisis tanto a nivel operativo como estructural:</p>
<ol type="1">
<li>La transición del registro histórico (RNPED) al sistema actual (RNPDNO) no fue un proceso de continuidad, sino de fractura. Las altas correlaciones entre las fases de “Búsqueda Generalizada” y la base de datos reciente, en contraste con su correlación negativa frente al padrón antiguo, demuestran matemáticamente que el Estado priorizó expedientes recientes. Esto derivó en una desaparición administrativa donde miles de casos históricos quedaron marginados de las estrategias oficiales de localización.</li>
<li>El crecimiento acelerado de registros a partir de 2018 no refleja necesariamente un incremento súbito en la tasa de desapariciones, sino la entrada en vigor de normativas que obligaron a visibilizar casos históricamente omitidos. Sin embargo, debido a la “cifra negra” y a los vacíos en los identificadores clave (FUB), los datos actuales siguen siendo una representación parcial que subestima la magnitud real de la crisis.</li>
<li>Aunque la desaparición es un fenómeno de alcance nacional, su comportamiento territorial es altamente desigual (índice de Gini &gt; 0.40). Entidades como el Estado de México y Tamaulipas no solo concentran el mayor volumen, sino que presentan una dispersión crónica que abarca décadas. Esto concluye que las estrategias federales homogéneas son ineficientes; se requieren intervenciones priorizadas, focalizadas y con un entendimiento del contexto de violencia local.</li>
</ol>
<p>En definitiva, este ejercicio demuestra que detrás de un archivo tabular aparentemente estático, existe una representación empírica y justificable de una crisis humanitaria. Bajo la lente de la minería de datos, logramos visibilizar el impacto directo que tienen las decisiones institucionales del Estado sobre el registro del fenómeno, alterando su progresión y atención a lo largo del tiempo. Más allá de los números, estas observaciones proporcionan la base técnica necesaria para exigir rendición de cuentas, optimizar los recursos de búsqueda y tomar decisiones basadas en evidencia que busquen mitigar la incertidumbre y la impunidad que crecen día con día en la sociedad mexicana.</p>
</section>
<section id="fuentes" class="level1">
<h1>Fuentes</h1>
<section id="row-6" class="level2">
<h2 class="anchored" data-anchor-id="row-6">Row</h2>
<div class="card">
<p>Comisión Nacional de Búsqueda. (s. f.). <em>Tipos de búsqueda</em>. Secretaría de Gobernación. Recuperado el 23 de marzo de 2026, de <a href="https://comisionacionaldebusqueda.segob.gob.mx/tipos-de-busqueda/" class="uri">https://comisionacionaldebusqueda.segob.gob.mx/tipos-de-busqueda/</a></p>
<p>Comisión Nacional de Búsqueda. (s. f.). <em>Consulta pública. Registro Nacional de Personas Desaparecidas y No Localizadas</em>. Recuperado el 23 de marzo de 2026, de <a href="https://consultapublicarnpdno.segob.gob.mx/" class="uri">https://consultapublicarnpdno.segob.gob.mx/</a></p>
<p>Gerardo Pérez, S. O. (2023, 9 de noviembre). <em>El Registro Nacional de Personas Desaparecidas y No Localizadas… una posibilidad para visibilizar la desaparición</em>. A dónde van los desaparecidos. Recuperado el 24 de marzo de 2026, de <a href="https://adondevanlosdesaparecidos.org/2023/11/09/el-registro-nacional-de-personas-desaparecidas-y-no-localizadas-una-posibilidad-para-visibilizar-la-desaparicion/" class="uri">https://adondevanlosdesaparecidos.org/2023/11/09/el-registro-nacional-de-personas-desaparecidas-y-no-localizadas-una-posibilidad-para-visibilizar-la-desaparicion/</a></p>
<p>Comisión Nacional de Búsqueda. (s. f.). <em>Versión estadística RNPDNO</em> [Dashboard]. Secretaría de Gobernación. Recuperado el 24 de marzo de 2026, de <a href="https://versionpublicarnpdno.segob.gob.mx/Dashboard/Index" class="uri">https://versionpublicarnpdno.segob.gob.mx/Dashboard/Index</a></p>
<p>Data Cívica. (2025, 2 de septiembre). <em>A quienes nos faltan: Datos para encontrarles 2025</em>. Observatorio sobre Desaparición e Impunidad en México. Recuperado el 24 de marzo de 2026, de <a href="https://odim.juridicas.unam.mx/detalle/1829/A%20quienes%20nos%20faltan%3A%20Datos%20para%20encontrarles%202025" class="uri">https://odim.juridicas.unam.mx/detalle/1829/A%20quienes%20nos%20faltan%3A%20Datos%20para%20encontrarles%202025</a></p>
<p>Red Lupa. (2025, 16 de mayo). <em>Informe nacional de personas desaparecidas 2025</em>. Instituto Mexicano de Derechos Humanos y Democracia. Recuperado el 25 de marzo de 2026, de <a href="https://imdhd.org/redlupa/informes-y-analisis/informes-nacionales/informe-nacional-de-personas-desaparecidas-2025/" class="uri">https://imdhd.org/redlupa/informes-y-analisis/informes-nacionales/informe-nacional-de-personas-desaparecidas-2025/</a></p>
<p>López Cruz, H. M., &amp; Romero Vargas, A. V. (2024, 14 de septiembre). <em>Las políticas públicas en los casos de personas desaparecidas en México</em>. Universidad La Salle; Observatorio sobre Desaparición e Impunidad en México. Recuperado el 25 de marzo de 2026, de <a href="https://odim.juridicas.unam.mx/detalle/1835/Las%20pol%C3%ADticas%20p%C3%BAblicas%20en%20los%20casos%20de%20personas%20desaparecidas%20en%20M%C3%A9xico" class="uri">https://odim.juridicas.unam.mx/detalle/1835/Las%20pol%C3%ADticas%20p%C3%BAblicas%20en%20los%20casos%20de%20personas%20desaparecidas%20en%20M%C3%A9xico</a></p>
<p>Flores, S., &amp; Nochebuena, M. (2026, 4 de marzo). <em>Sin acceso a las prendas: Ignoran autoridades peticiones de familiares</em>. A dónde van los desaparecidos. Recuperado el 26 de marzo de 2026, de <a href="https://adondevanlosdesaparecidos.org/2026/03/04/sin-acceso-a-las-prendas-ignoran-autoridades-peticiones-de-familiares/" class="uri">https://adondevanlosdesaparecidos.org/2026/03/04/sin-acceso-a-las-prendas-ignoran-autoridades-peticiones-de-familiares/</a></p>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>